// <auto-generated />

using System;

namespace CIMV2
{
    /// <summary>
    /// The Win32_OnBoardDevice class represents common adapter devices built into the motherboard (system board). <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {AEECF151-D0EA-11d2-ABFC-00805F538618} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OnBoardDevice
    {
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// CreationClassName indicates the name of the class or the subclass used in the creation of an instance. <br/>
        /// When used with the other key properties of this class, this property allows all instances of this class and its subclasses to be uniquely identified. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CreationClassName { get; set; }
        /// <summary>
        /// The Description property describes the on-board device and is filled by the manufacturer of the device. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: Description <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The DeviceType property indicates the type of device being represented. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 DeviceType { get; set; }
        /// <summary>
        /// The Enabled property indicates whether or not the on-board device is available for use. <br/>
        /// Values: TRUE or FALSE. <br/>
        /// A value of TRUE indicates the device is enabled for use. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Enabled { get; set; }
        /// <summary>
        /// A physical component can be hot swapped if it is possible to replace the element with a physically different but equivalent one while the containing package has power applied to it (i.e., is &apos;on&apos;). <br/>
        /// For example, a fan component may be designed to be hot swapped. <br/>
        /// All components that can be hot swapped are inherently removable and replaceable . <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean HotSwappable { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// The name of the organization responsible for producing the physical element. <br/>
        /// This may be the entity from whom the element is purchased, but this is not necessarily true. <br/>
        /// The latter information is contained in the Vendor property of CIM_Product. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Manufacturer { get; set; }
        /// <summary>
        /// The name by which the physical element is generally known. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Model { get; set; }
        /// <summary>
        /// The Name property defines the label by which the object is known. <br/>
        /// When subclassed, the Name property can be overridden to be a Key property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// OtherIdentifyingInfo captures additional data, beyond asset tag information, that could be used to identify a physical element. <br/>
        /// One example is bar code data associated with an element that also has an asset tag. <br/>
        /// Note that if only bar code data is available and is unique/able to be used as an element key, this property would be NULL and the bar code data used as the class key, in the tag property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String OtherIdentifyingInfo { get; set; }
        /// <summary>
        /// The part number assigned by the organization responsible for producing or manufacturing the physical element. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String PartNumber { get; set; }
        /// <summary>
        /// Boolean indicating that the physical element is powered on (TRUE), or is currently off (FALSE). <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean PoweredOn { get; set; }
        /// <summary>
        /// A physical component is removable if it is designed to be taken in and out of the physical container in which it is normally found, without impairing the function of the overall packaging. <br/>
        /// A component can still be removable if power must be &apos;off&apos; in order to perform the removal. <br/>
        /// If power can be &apos;on&apos; and the component removed, then the element is removable and can be hot swapped. <br/>
        /// For example, an upgradeable processor chip is removable. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Removable { get; set; }
        /// <summary>
        /// A physical component is replaceable  if it is possible to replace (FRU or upgrade) the element with a physically different one. <br/>
        /// For example, some computer systems allow the main processor chip to be upgraded to one of a higher clock rating. <br/>
        /// In this case, the processor is said to be replaceable . <br/>
        /// All removable components are inherently replaceable . <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Replaceable { get; set; }
        /// <summary>
        /// A manufacturer-allocated number used to identify the PhysicalElement. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SerialNumber { get; set; }
        /// <summary>
        /// The stock keeping unit number for this physical element. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SKU { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// The Tag property uniquely identifies the on-board device connected to the system. <br/>
        /// Example: On Board Device 1 <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: Tag <br/>
        ///  <br/>
        /// </summary>
        public String Tag { get; set; }
        /// <summary>
        /// A string indicating the version of the physical element. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Version { get; set; }
    }

    /// <summary>
    /// The Win32_OperatingSystem class represents an operating system installed on a Win32 computer system. <br/>
    /// Any operating system that can be installed on a Win32 system is a descendent (or member) of this class. <br/>
    /// Example: Microsoft Windows 95. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {8502C4DE-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OperatingSystem
    {
        /// <summary>
        /// The BootDevice property indicates the name of the disk drive from which the Win32 operating system boots. <br/>
        /// Example: \\Device\Harddisk0. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String BootDevice { get; set; }
        /// <summary>
        /// The BuildNumber property indicates the build number of the operating system. <br/>
        /// It can be used for more precise versioning information than product release version numbers <br/>
        /// Example: 1381 <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String BuildNumber { get; set; }
        /// <summary>
        /// The BuildType property indicates the type of build used for the operating system. <br/>
        /// Examples are retail build and checked build. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String BuildType { get; set; }
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// The CodeSet property indicates the code page value used by the operating system. <br/>
        /// A code page contains a character table used by the operating system to translate strings for different languages. <br/>
        /// The American National Standards Institute (ANSI) lists values that represent defined code pages. <br/>
        /// If the operating system does not use an ANSI code page, this member will be set to 0. <br/>
        /// The CodeSet string can use up to six characters to define the code page value. <br/>
        /// Example: 1255. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CodeSet { get; set; }
        /// <summary>
        /// The CountryCode property indicates the code for the country/regionused by the operating system. <br/>
        /// Values are based on international phone dialing prefixes (also referred to as IBM country/region codes). <br/>
        /// The CountryCode string can use up to six characters to define the country/region code value. <br/>
        /// Example: 1 for the United States) <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CountryCode { get; set; }
        /// <summary>
        /// CreationClassName indicates the name of the class or the subclass used in the creation of an instance. <br/>
        /// When used with the other key properties of this class, this property allows all instances of this class and its subclasses to be uniquely identified. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CreationClassName { get; set; }
        /// <summary>
        /// CSCreationClassName contains the scoping computer system&apos;s creation class name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_ComputerSystem.CreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String CSCreationClassName { get; set; }
        /// <summary>
        /// The CSDVersion property contains a null-terminated string, that indicates the latest Service Pack installed on the computer system. <br/>
        /// If no Service Pack is installed, the string is NULL. <br/>
        /// For computer systems running Windows 95, this property contains a null-terminated string that provides arbitrary additional information about the operating system. <br/>
        /// Example: Service Pack 3. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CSDVersion { get; set; }
        /// <summary>
        /// CSName contains the scoping computer system&apos;s name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_ComputerSystem.Name <br/>
        ///  <br/>
        /// </summary>
        public String CSName { get; set; }
        /// <summary>
        /// CurrentTimeZone indicates the number of minutes the operating system is offset from Greenwich Mean Time. <br/>
        /// Either the number is positive, negative or zero. <br/>
        ///  <br/>
        /// cimtype: sint16 <br/>
        ///  <br/>
        /// units: minutes <br/>
        ///  <br/>
        /// </summary>
        public short CurrentTimeZone { get; set; }
        /// <summary>
        /// If true, indicates that 32-bit applications are running with Data Execution Prevention (DEP) applied. <br/>
        /// (false if DataExecutionPrevention_Available = false) <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean DataExecutionPrevention_32BitApplications { get; set; }
        /// <summary>
        /// If true, indicates that the hardware supports Windows Data Execution Prevention (DEP) technology. <br/>
        /// DEP ensures that all memory locations are marked with a non-executable attribute unless the memory location explicitly contains executable code. <br/>
        /// This can help mitigate certain types of buffer overrun security exploits. <br/>
        /// If DEP is available, 64-bit applications are automatically protected. <br/>
        /// To determine if DEP has been enabled for 32-bit applications and drivers, use the DataExecutionPrevention_ properties <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean DataExecutionPrevention_Available { get; set; }
        /// <summary>
        /// If true, indicates that drivers are running with Data Execution Prevention (DEP) applied. <br/>
        /// (false if DataExecutionPrevention_Available = false) <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean DataExecutionPrevention_Drivers { get; set; }
        /// <summary>
        /// The DataExecutionPrevention_SupportPolicy indicates which one of four Data Execution Prevention (DEP) settings is applied. <br/>
        /// Each setting varies by the extent to which DEP is applied to 32-bit applications. <br/>
        /// Note that DEP is always applied to the Windows kernel. <br/>
        /// Always On (not available in the user interface) indicates that DEP is enabled for all 32-bit applications on the machine with no exceptions. <br/>
        /// OptOut indicates DEP is on by default for all 32-bit applications and that a user or administrator must explicitly remove support for a 32-bit application by adding to an exceptions list. <br/>
        /// OptIn indicates DEP is on for a limited number of binaries, the kernel, and all Windows services but it is off by default for all 32-bit applications; a user or administrator must explicitly choose the AlwaysOn (not available in the user interface) or OptOut setting before DEP can be applied to 32-bit applications. <br/>
        /// AlwaysOff (not available in the user interface) indicates DEP is turned off for all 32-bit applications on the machine. <br/>
        ///  <br/>
        /// cimtype: uint8 <br/>
        ///  <br/>
        /// </summary>
        public byte DataExecutionPrevention_SupportPolicy { get; set; }
        /// <summary>
        /// The Debug property indicates whether the operating system is a checked (debug) build. <br/>
        /// Checked builds provide error checking, argument verification, and system debugging code. <br/>
        /// Additional code in a checked binary generates a kernel debugger error message and breaks into the debugger. <br/>
        /// This helps  immediately determine the cause and location of the error. <br/>
        /// Performance suffers in the checked build due to the additional code that is executed. <br/>
        /// Values: TRUE or FALSE, A value of TRUE indicates the debugging version of User.exe is installed. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Debug { get; set; }
        /// <summary>
        /// The Description property provides a description of the Windows operating system. <br/>
        /// Some user interfaces (those that allow editing of this description) limit its length to 48 characters. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: Description <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// Boolean indicating whether the operating system is distributed across several computer system nodes. <br/>
        /// If so, these nodes should be grouped as a cluster. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Distributed { get; set; }
        /// <summary>
        /// The EncryptionLevel property specifies if the encryption level for secure transactions is 40-bit, 128-bit, or n-bit encryption. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 EncryptionLevel { get; set; }
        /// <summary>
        /// The ForegroundApplicationBoost property indicates the increase in priority given to the foreground application. <br/>
        /// On computer systems running Windows NT 4.0 and Windows 2000, application boost is implemented by giving an application more execution time slices (quantum lengths). <br/>
        /// A ForegroundApplicationBoost value of 0 indicates the system boosts the quantum length by 6; if 1, then 12; and if 2 then 18. <br/>
        /// On Windows NT 3.51 and earlier, application boost is implemented by increasing the scheduling priority. <br/>
        /// For these systems, the scheduling priority is increased by the value of this property. <br/>
        /// The default value is 2. <br/>
        ///  <br/>
        /// cimtype: uint8 <br/>
        ///  <br/>
        /// </summary>
        public byte ForegroundApplicationBoost { get; set; }
        /// <summary>
        /// Number of kilobytes of physical memory currently unused and available <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: kilobytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 FreePhysicalMemory { get; set; }
        /// <summary>
        /// The total number of KBytes that can be mapped into the OperatingSystem&apos;s paging files without causing any other pages to be swapped out. <br/>
        /// 0 indicates that there are no paging files. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: kilobytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 FreeSpaceInPagingFiles { get; set; }
        /// <summary>
        /// Number of kilobytes of virtual memory currently unused and available. <br/>
        /// For example, this may be calculated by adding the amount of free RAM to the amount of free paging space (i.e., adding the properties, FreePhysicalMemory and FreeSpaceInPagingFiles). <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: kilobytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 FreeVirtualMemory { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// The LargeSystemCache property indicates whether to optimize memory for applications (value=0) or for system performance (value=1). <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 LargeSystemCache { get; set; }
        /// <summary>
        /// Time when the operating system was last booted <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime LastBootUpTime { get; set; }
        /// <summary>
        /// Operating system&apos;s notion of the local date and time of day. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime LocalDateTime { get; set; }
        /// <summary>
        /// The Locale property indicates the language identifier used by the operating system. <br/>
        /// A language identifier is a standard international numeric abbreviation for a country or region. <br/>
        /// Each language has a unique language identifier (LANGID), a 16-bit value that consists of a primary language identifier and a secondary language identifier. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Locale { get; set; }
        /// <summary>
        /// The Manufacturer property indicates the name of the operating system manufacturer. <br/>
        /// For Win32 systems this value will be Microsoft Corporation. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Manufacturer { get; set; }
        /// <summary>
        /// Maximum number of process contexts the operating system can support. <br/>
        /// If there is no fixed maximum, the value should be 0. <br/>
        /// On systems that have a fixed maximum, this object can help diagnose failures that occur when the maximum is reached. <br/>
        /// If unknown, enter -1. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 MaxNumberOfProcesses { get; set; }
        /// <summary>
        /// Maximum number of kilobytes of memory that can be allocated to a process. <br/>
        /// For operating systems with no virtual memory, this value is typically equal to the total amount of physical memory minus memory used by the BIOS and OS. <br/>
        /// For some operating systems, this value may be infinity - in which case, 0 should be entered. <br/>
        /// In other cases, this value could be a constant - for example, 2G or 4G. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: kilobytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 MaxProcessMemorySize { get; set; }
        /// <summary>
        /// The MUILanguages property indicates the MUI Languages installed in the system. <br/>
        /// Example: en-us. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String[] MUILanguages { get; set; }
        /// <summary>
        /// Name of the operating system instance within a computer system. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// Number of user licenses for the operating system. <br/>
        /// If unlimited, enter 0. <br/>
        /// If unknown, enter -1. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 NumberOfLicensedUsers { get; set; }
        /// <summary>
        /// Number of process contexts currently loaded or running on the operating system. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 NumberOfProcesses { get; set; }
        /// <summary>
        /// Number of user sessions for which the operating system is currently storing state information <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 NumberOfUsers { get; set; }
        /// <summary>
        /// The OperatingSystemSKU property identifies the SKU of the operating system. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 OperatingSystemSKU { get; set; }
        /// <summary>
        /// The Organization property indicates the registered user&apos;s (of the operating system) company name. <br/>
        /// Example: Microsoft Corporation. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Organization { get; set; }
        /// <summary>
        /// The OSArchitecture property indicates the Architecture of the operating system.Example: 32-bit, 64-bit Intel, 64-bit AMD <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String OSArchitecture { get; set; }
        /// <summary>
        /// The OSLanguage property indicates which language version of the operating system is installed. <br/>
        /// Example: 0x0807 (German, Switzerland) <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 OSLanguage { get; set; }
        /// <summary>
        /// The OSProductSuite property identifies installed and licensed system product additions to the operating system. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 OSProductSuite { get; set; }
        /// <summary>
        /// A integer indicating the type of operating system. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 OSType { get; set; }
        /// <summary>
        /// A string describing the manufacturer and operating system type - used when the operating system property, OSType, is set to 1 (&quot;Other&quot;). <br/>
        /// The format of the string inserted in OtherTypeDescription should be similar in format to the Values strings defined for OSType. <br/>
        /// OtherTypeDescription should be set to NULL when OSType is any value other than 1. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String OtherTypeDescription { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean PAEEnabled { get; set; }
        /// <summary>
        /// The PlusProductID property contains the product identification number for the Windows Plus! operating system enhancement software (if installed). <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String PlusProductID { get; set; }
        /// <summary>
        /// The PlusVersionNumber property contains the version number of the Windows Plus! operating system enhancement software (if installed). <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String PlusVersionNumber { get; set; }
        /// <summary>
        /// The PortableOperatingSystem property indicates if theOperating System is booting from a supported locally connected storagedevice. <br/>
        /// Values: TRUE or FALSE, A value of TRUE indicates the OperatingSystem was booted from a supported locally connected storage device. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean PortableOperatingSystem { get; set; }
        /// <summary>
        /// The Primary property determines whether this is the primary operating system. <br/>
        /// Values: TRUE or FALSE. <br/>
        /// A value of TRUE indicates this is the primary operating system. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Primary { get; set; }
        /// <summary>
        /// The ProductType property indicates additional information about the system. <br/>
        /// This member can be one of the following values: <br/>
        /// 1 - Work Station <br/>
        /// 2 - Domain Controller <br/>
        /// 3 - Server <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ProductType { get; set; }
        /// <summary>
        /// The RegisteredUser property indicates the name of the registered user of the operating system. <br/>
        /// Example: Jane Doe <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String RegisteredUser { get; set; }
        /// <summary>
        /// The SerialNumber property indicates the operating system product serial identification number. <br/>
        /// Example:10497-OEM-0031416-71674. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SerialNumber { get; set; }
        /// <summary>
        /// The ServicePackMajorVersion property indicates the major version number of the service pack installed on the computer system. <br/>
        /// If no service pack has been installed, the value is zero. <br/>
        /// ServicePackMajorVersion is valid for computers running Windows 2000 and later (NULL otherwise). <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 ServicePackMajorVersion { get; set; }
        /// <summary>
        /// The ServicePackMinorVersion property indicates the minor version number of the service pack installed on the computer system. <br/>
        /// If no service pack has been installed, the value is zero. <br/>
        /// ServicePackMinorVersion is valid for computers running Windows 2000 and later (NULL otherwise). <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 ServicePackMinorVersion { get; set; }
        /// <summary>
        /// The total number of kilobytes that can be stored in the operating system&apos;s paging files. <br/>
        /// Note that this number does not represent the actual physical size of the paging file on disk. <br/>
        /// 0 indicates that there are no paging files. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: kilobytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 SizeStoredInPagingFiles { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// The SuiteMask property indicates a set of bit flags that identify the product suites available on the system. <br/>
        /// This member can be a combination of the following values: <br/>
        /// 0 - Windows Server 2003, Small Business Edition <br/>
        /// 1 - Windows Server 2003, Enterprise Edition <br/>
        /// 2 - Windows Server 2003, Backoffice Edition <br/>
        /// 3 - Windows Server 2003, Communications Edition <br/>
        /// 4 - Microsoft Terminal Services <br/>
        /// 5 - Windows Server 2003, Small Business Edition Restricted <br/>
        /// 6 - Windows XP Embedded <br/>
        /// 7 - Windows Server 2003, Datacenter Edition <br/>
        /// 8 - Single User <br/>
        /// 9 - Windows XP Home Edition <br/>
        /// 10 - Windows Server 2003, Web Edition <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 SuiteMask { get; set; }
        /// <summary>
        /// The SystemDevice property indicates the physical disk partition the operating system is installed on. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SystemDevice { get; set; }
        /// <summary>
        /// The SystemDirectory property indicates the system directory of the operating system. <br/>
        /// Example: C:\WINDOWS\SYSTEM32 <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SystemDirectory { get; set; }
        /// <summary>
        /// The SystemDrive property contains the letter of the disk drive that the operating system resides on. <br/>
        /// Example: C: <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SystemDrive { get; set; }
        /// <summary>
        /// Total swap space in kilobytes. <br/>
        /// This value may be NULL (unspecified) if swap space is not distinguished from page files. <br/>
        /// However, some operating systems distinguish these concepts. <br/>
        /// For example, in UNIX, whole processes can be &apos;swapped out&apos; when the free page list falls and remains below a specified amount. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: kilobytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 TotalSwapSpaceSize { get; set; }
        /// <summary>
        /// Number of kilobytes of virtual memory. <br/>
        /// For example, this may be calculated by adding the amount of total RAM to the amount of paging space (i.e., adding the amount of memory in/aggregated by the computer system to the property, SizeStoredInPagingFiles. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: kilobytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 TotalVirtualMemorySize { get; set; }
        /// <summary>
        /// The total amount of physical memory (in Kbytes) available to the OperatingSystem. <br/>
        /// This value does not necessarily indicate the true amount of physical memory, but what is reported to the OperatingSystem as available to it. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: kilobytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 TotalVisibleMemorySize { get; set; }
        /// <summary>
        /// The Version property indicates the version number of the operating system. <br/>
        /// Example: 4.0 <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: Version <br/>
        ///  <br/>
        /// </summary>
        public String Version { get; set; }
        /// <summary>
        /// The WindowsDirectory property indicates the Windows directory of the operating system. <br/>
        /// Example: C:\WINDOWS <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String WindowsDirectory { get; set; }
    }

    /// <summary>
    /// This class represents status of the Optional Features present on the operating system <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {0827250D-BA3E-11d2-B361-00105A1F77A2} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OptionalFeature
    {
        /// <summary>
        /// Caption property is a optional feature display name <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// The Description property provides a textual description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// This identifies the state of the optional feature. <br/>
        /// It shows if the Optional feature is enabled, disabled, absent or unknown <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 InstallState { get; set; }
        /// <summary>
        /// This property represents the name of the optional feature <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
    }

    /// <summary>
    /// The Win32_OSRecoveryConfiguration class represents the types of information that will be gathered from memory when the operating system fails. <br/>
    /// This includes boot failures and system crashes. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {8502C4E8-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OSRecoveryConfiguration
    {
        /// <summary>
        /// The AutoReboot property determines whether the system will automatically reboot during a recovery operation. <br/>
        /// Values: TRUE or FALSE. <br/>
        /// If TRUE, the system will automatically rebooted. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean AutoReboot { get; set; }
        /// <summary>
        /// A short textual description (one-line string) of the CIM_Setting object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// The DebugFilePath property indicates the path to the debug file. <br/>
        /// A debug file is created with the memory state of the machine after a machine failure. <br/>
        /// Example: %systemRoot%\Memory.dmp <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String DebugFilePath { get; set; }
        /// <summary>
        /// The DebugInfoType property indicates what type of debugging information is to be written to the log file. <br/>
        /// Values: 0 = None <br/>
        /// 1 = Complete memory dump <br/>
        /// 2 = Kernel memory dump <br/>
        /// 3 = Small memory dump (64KB) <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 DebugInfoType { get; set; }
        /// <summary>
        /// A textual description of the CIM_Setting object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The ExpandedDebugFilePath property is an expanded version of the DebugFilePath property. <br/>
        /// Example: C:\WinNT\Memory.dmp <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ExpandedDebugFilePath { get; set; }
        /// <summary>
        /// The ExpandedMiniDumpDirectory property is an expanded version of the MiniDumpDirectory property. <br/>
        /// Example: C:\WinNT\MiniDump <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ExpandedMiniDumpDirectory { get; set; }
        /// <summary>
        /// The KernelDumpOnly property has been deprecated in favor of the DebugInfoType property in the same class. <br/>
        /// All future work should use this new property. <br/>
        /// The KernelDumpOnly property indicates whether only kernel debug information will be written to the debug log file. <br/>
        /// Values TRUE or FALSE. <br/>
        /// If TRUE, then only the state of kernel is written to a file in the event of a system failure. <br/>
        /// If FALSE, the system will try to log the state of the memory and any devices that can provide information about the system when it failed. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean KernelDumpOnly { get; set; }
        /// <summary>
        /// The MiniDumpDirectory property indicates the directory where small memory dump files will be recorded and accumulated. <br/>
        /// Example: %systemRoot%\MiniDump <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String MiniDumpDirectory { get; set; }
        /// <summary>
        /// The Name property contains an identifying name for this instance of the Win32_OSRecoveryConfiguration class. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The OverwriteExistingDebugFile property indicates whether a new log file will overwrite an existing one. <br/>
        /// Values: TRUE or FALSE. <br/>
        /// If TRUE, the existing debug file will be overwritten. <br/>
        /// If FALSE, a log file is not written if the filename already exists. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean OverwriteExistingDebugFile { get; set; }
        /// <summary>
        /// The SendAdminAlert property indicates whether or not an alert message will be sent to the system administrator in the event of an operating system failure. <br/>
        /// Values: TRUE or FALSE. <br/>
        /// If TRUE, the system will send an alert to the system administrator. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean SendAdminAlert { get; set; }
        /// <summary>
        /// The identifier by which the CIM_Setting object is known. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SettingID { get; set; }
        /// <summary>
        /// The WriteDebugInfo property has been deprecated in favor of the DebugInfoType property in the same class. <br/>
        /// All future work should use this new property. <br/>
        /// The WriteDebugInfo property indicates whether or not debugging information is to be written to a log file. <br/>
        /// Values: TRUE or FALSE. <br/>
        /// If TRUE, debug information is written to a file. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean WriteDebugInfo { get; set; }
        /// <summary>
        /// The WriteToSystemLog property indicates whether or not events will be written to a system log. <br/>
        /// Values: TRUE or FALSE. <br/>
        /// If TRUE, information will be written to a system log file. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean WriteToSystemLog { get; set; }
    }

    /// <summary>
    /// The Setting class represents configuration-related and operational parameters for one or more ManagedSystemElement(s). <br/>
    /// A ManagedSystemElement may have multiple Setting objects associated with it. <br/>
    /// The current operational values for an Element&apos;s parameters are reflected by properties in the Element itself or by properties in its associations. <br/>
    /// These properties do not have to be the same values present in the Setting object. <br/>
    /// For example, a modem may have a Setting baud rate of 56Kb/sec but be operating at 19.2Kb/sec. <br/>
    ///  <br/>
    /// provider: MSIProv <br/>
    ///  <br/>
    /// uuid: {023763EC-E3D2-11d2-8601-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_ODBCAttribute
    {
        /// <summary>
        /// The name of the ODBC attribute. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Attribute { get; set; }
        /// <summary>
        /// A short textual description (one-line string) of the CIM_Setting object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// A textual description of the CIM_Setting object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Driver { get; set; }
        /// <summary>
        /// The identifier by which the CIM_Setting object is known. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SettingID { get; set; }
        /// <summary>
        /// The value of this attribute. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Value { get; set; }
    }

    /// <summary>
    /// The Setting class represents configuration-related and operational parameters for one or more ManagedSystemElement(s). <br/>
    /// A ManagedSystemElement may have multiple Setting objects associated with it. <br/>
    /// The current operational values for an Element&apos;s parameters are reflected by properties in the Element itself or by properties in its associations. <br/>
    /// These properties do not have to be the same values present in the Setting object. <br/>
    /// For example, a modem may have a Setting baud rate of 56Kb/sec but be operating at 19.2Kb/sec. <br/>
    ///  <br/>
    /// provider: MSIProv <br/>
    ///  <br/>
    /// uuid: {100985A4-E3D2-11d2-8601-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_ODBCSourceAttribute
    {
        /// <summary>
        /// The name of the data source attribute. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Attribute { get; set; }
        /// <summary>
        /// A short textual description (one-line string) of the CIM_Setting object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// Token name for the data source within its package to which this attribute applies. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String DataSource { get; set; }
        /// <summary>
        /// A textual description of the CIM_Setting object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The identifier by which the CIM_Setting object is known. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SettingID { get; set; }
        /// <summary>
        /// The value for this data source attribute. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Value { get; set; }
    }

    /// <summary>
    ///  <br/>
    /// provider: Win32_OfflineFilesConfigurationProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesUserConfiguration
    {
        /// <summary>
        /// An array of strings containing administratively assigned offline files. <br/>
        /// Each string contains a file path <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String[] AssignedOfflineFiles { get; set; }
        /// <summary>
        /// Indicate if the configuration settings are taking affect <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean IsConfiguredByWMI { get; set; }
        /// <summary>
        /// If true, the Make Available Offline button is removed from Explorer. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean MakeAvailableOfflineButtonRemoved { get; set; }
        /// <summary>
        /// If true, the Work Offline button is removed from Explorer. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean WorkOfflineButtonRemoved { get; set; }
    }

    /// <summary>
    ///  <br/>
    /// uuid: {db089a12-f250-47aa-b9d0-89806d928ba6} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesAssociatedItems
    {
    }

    /// <summary>
    ///  <br/>
    /// provider: Win32_OfflineFilesProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesChangeInfo
    {
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean CreatedOffline { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean DeletedOffline { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Dirty { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ModifiedAttributes { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ModifiedData { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ModifiedTime { get; set; }
    }

    /// <summary>
    /// This class represents the association between an operating system and the autochk settings that apply to the disks on the machine.Note that the setting is associated to operating system rather than computer system since there can be one or more operating systems installed on the machine, each with its own autochk settings. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32a <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OperatingSystemAutochkSetting
    {
    }

    /// <summary>
    /// This class represents any ODBC drivers that are to be installed as part of a particular product. <br/>
    ///  <br/>
    /// provider: MSIProv <br/>
    ///  <br/>
    /// uuid: {45BD8DD2-DB33-11d2-85FC-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_ODBCDriverSpecification
    {
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// An identifier used in conjunction with other keys to uniquely identify the check <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CheckID { get; set; }
        /// <summary>
        /// The CheckMode property is used to indicate whether the condition is  expected to exist or not exist in the environment. <br/>
        /// When the value is True, the condition is expected to exist  (e.g., a file is expected to be on a system) so invoke() is expected to  return True. <br/>
        /// When the value is False, the condition is not expect to exist  (e.g., a file is not to be on a system) so invoke is expected to return false <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean CheckMode { get; set; }
        /// <summary>
        /// A description of the objects. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// Token name for the driver within its package. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Driver { get; set; }
        /// <summary>
        /// The FileID of the Win32_FileSpecification representing this driver. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String File { get; set; }
        /// <summary>
        /// The name used to identify this software element <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.Name <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The FileID of the Win32_FileSpecification representing this drivers setup dll. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SetupFile { get; set; }
        /// <summary>
        /// This is an identifier for this software element. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementID <br/>
        ///  <br/>
        /// </summary>
        public String SoftwareElementID { get; set; }
        /// <summary>
        /// The software element state of a software element <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementState <br/>
        ///  <br/>
        /// </summary>
        public UInt16 SoftwareElementState { get; set; }
        /// <summary>
        /// The target operating system of the this software element. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.TargetOperatingSystem <br/>
        ///  <br/>
        /// </summary>
        public UInt16 TargetOperatingSystem { get; set; }
        /// <summary>
        /// Version should be in the form &lt;Major&gt;.&lt;Minor&gt;.&lt;Revision&gt; or &lt;Major&gt;.&lt;Minor&gt;&lt;letter&gt;&lt;revision&gt; <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.Version <br/>
        ///  <br/>
        /// </summary>
        public String Version { get; set; }
    }

    /// <summary>
    /// This class specifies any Data Sources (DSNs) that need to be registered as part of an installation. <br/>
    ///  <br/>
    /// provider: MSIProv <br/>
    ///  <br/>
    /// uuid: {1F20B83E-DB33-11d2-85FC-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_ODBCDataSourceSpecification
    {
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// An identifier used in conjunction with other keys to uniquely identify the check <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CheckID { get; set; }
        /// <summary>
        /// The CheckMode property is used to indicate whether the condition is  expected to exist or not exist in the environment. <br/>
        /// When the value is True, the condition is expected to exist  (e.g., a file is expected to be on a system) so invoke() is expected to  return True. <br/>
        /// When the value is False, the condition is not expect to exist  (e.g., a file is not to be on a system) so invoke is expected to return false <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean CheckMode { get; set; }
        /// <summary>
        /// Token name for the data source within its package. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String DataSource { get; set; }
        /// <summary>
        /// A description of the objects. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The associated ODBC driver name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String DriverDescription { get; set; }
        /// <summary>
        /// The name used to identify this software element <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.Name <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The type of registration for this data source. <br/>
        /// ) indicates per machine, <br/>
        /// 1 indicates per user. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Registration { get; set; }
        /// <summary>
        /// This is an identifier for this software element. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementID <br/>
        ///  <br/>
        /// </summary>
        public String SoftwareElementID { get; set; }
        /// <summary>
        /// The software element state of a software element <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementState <br/>
        ///  <br/>
        /// </summary>
        public UInt16 SoftwareElementState { get; set; }
        /// <summary>
        /// The target operating system of the this software element. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.TargetOperatingSystem <br/>
        ///  <br/>
        /// </summary>
        public UInt16 TargetOperatingSystem { get; set; }
        /// <summary>
        /// Version should be in the form &lt;Major&gt;.&lt;Minor&gt;.&lt;Revision&gt; or &lt;Major&gt;.&lt;Minor&gt;&lt;letter&gt;&lt;revision&gt; <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.Version <br/>
        ///  <br/>
        /// </summary>
        public String Version { get; set; }
    }

    /// <summary>
    /// Instances of this class represent any ODBC Translators that are included as part of a products installation. <br/>
    ///  <br/>
    /// provider: MSIProv <br/>
    ///  <br/>
    /// uuid: {51E28842-DB33-11d2-85FC-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_ODBCTranslatorSpecification
    {
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// An identifier used in conjunction with other keys to uniquely identify the check <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CheckID { get; set; }
        /// <summary>
        /// The CheckMode property is used to indicate whether the condition is  expected to exist or not exist in the environment. <br/>
        /// When the value is True, the condition is expected to exist  (e.g., a file is expected to be on a system) so invoke() is expected to  return True. <br/>
        /// When the value is False, the condition is not expect to exist  (e.g., a file is not to be on a system) so invoke is expected to return false <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean CheckMode { get; set; }
        /// <summary>
        /// A description of the objects. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The FileID of the Win32_FileSpecification representing this translator. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String File { get; set; }
        /// <summary>
        /// The name used to identify this software element <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.Name <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The FileID of the Win32_FileSpecification representing this translators setup dll. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SetupFile { get; set; }
        /// <summary>
        /// This is an identifier for this software element. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementID <br/>
        ///  <br/>
        /// </summary>
        public String SoftwareElementID { get; set; }
        /// <summary>
        /// The software element state of a software element <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementState <br/>
        ///  <br/>
        /// </summary>
        public UInt16 SoftwareElementState { get; set; }
        /// <summary>
        /// The target operating system of the this software element. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.TargetOperatingSystem <br/>
        ///  <br/>
        /// </summary>
        public UInt16 TargetOperatingSystem { get; set; }
        /// <summary>
        /// Token name for the translator within its package. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Translator { get; set; }
        /// <summary>
        /// Version should be in the form &lt;Major&gt;.&lt;Minor&gt;.&lt;Revision&gt; or &lt;Major&gt;.&lt;Minor&gt;&lt;letter&gt;&lt;revision&gt; <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.Version <br/>
        ///  <br/>
        /// </summary>
        public String Version { get; set; }
    }

    /// <summary>
    ///  <br/>
    /// provider: Win32_OfflineFilesProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesItem
    {
        /// <summary>
        ///  <br/>
        /// cimtype: object:Win32_OfflineFilesChangeInfo <br/>
        ///  <br/>
        /// </summary>
        public Object ChangeInfo { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: object:Win32_OfflineFilesConnectionInfo <br/>
        ///  <br/>
        /// </summary>
        public Object ConnectionInfo { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: object:Win32_OfflineFilesDirtyInfo <br/>
        ///  <br/>
        /// </summary>
        public Object DirtyInfo { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Encrypted { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: object:Win32_OfflineFilesFileSysInfo <br/>
        ///  <br/>
        /// </summary>
        public Object FileSysInfo { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ItemName { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ItemPath { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ItemType { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ParentItemPath { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: object:Win32_OfflineFilesPinInfo <br/>
        ///  <br/>
        /// </summary>
        public Object PinInfo { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Sparse { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: object:Win32_OfflineFilesSuspendInfo <br/>
        ///  <br/>
        /// </summary>
        public Object SuspendInfo { get; set; }
    }

    /// <summary>
    ///  <br/>
    /// provider: Win32_OfflineFilesConfigurationProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesBackgroundSync
    {
        /// <summary>
        /// If true, enable background synchronization for shares that the user has forced into work offline mode <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean BackgroundSyncWorkOfflineSharesEnabled { get; set; }
        /// <summary>
        /// The length of time, in minutes, when background synchronization is disabled. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 BlockOutDurationMin { get; set; }
        /// <summary>
        /// The time of the day when background synchronization is disabled. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 BlockOutStartTimeHoursMinutes { get; set; }
        /// <summary>
        /// The maximum time, in minutes, until a synchronization operation must start. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 MaxTimeBetweenSyncs { get; set; }
        /// <summary>
        /// The synchronization interval, in minutes. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 SyncInterval { get; set; }
        /// <summary>
        /// The amount of time, in minutes, by which the synchronization interval can vary. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 SyncVariance { get; set; }
    }

    /// <summary>
    /// This association relates an MSI check with any setting information it requires. <br/>
    ///  <br/>
    /// provider: MSIProv <br/>
    ///  <br/>
    /// uuid: {2B306494-DB33-11d2-85FC-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_ODBCDriverAttribute
    {
    }

    /// <summary>
    /// This association relates an MSI check with any setting information it requires. <br/>
    ///  <br/>
    /// provider: MSIProv <br/>
    ///  <br/>
    /// uuid: {0E5ACD14-DB33-11d2-85FC-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_ODBCDataSourceAttribute
    {
    }

    /// <summary>
    ///  <br/>
    /// provider: Win32_OfflineFilesProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesPinInfo
    {
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Pinned { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 PinnedForComputer { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 PinnedForFolderRedirection { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 PinnedForUser { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 PinnedForUserByPolicy { get; set; }
    }

    /// <summary>
    ///  <br/>
    /// provider: Win32_OfflineFilesProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesFileSysInfo
    {
        /// <summary>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 LocalAttributes { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: DATETIME <br/>
        ///  <br/>
        /// </summary>
        public DateTime LocalChangeTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: DATETIME <br/>
        ///  <br/>
        /// </summary>
        public DateTime LocalCreationTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: DATETIME <br/>
        ///  <br/>
        /// </summary>
        public DateTime LocalLastAccessTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: DATETIME <br/>
        ///  <br/>
        /// </summary>
        public DateTime LocalLastWriteTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: sint64 <br/>
        ///  <br/>
        /// </summary>
        public long LocalSize { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 OriginalAttributes { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: DATETIME <br/>
        ///  <br/>
        /// </summary>
        public DateTime OriginalChangeTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: DATETIME <br/>
        ///  <br/>
        /// </summary>
        public DateTime OriginalCreationTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: DATETIME <br/>
        ///  <br/>
        /// </summary>
        public DateTime OriginalLastAccessTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: DATETIME <br/>
        ///  <br/>
        /// </summary>
        public DateTime OriginalLastWriteTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: sint64 <br/>
        ///  <br/>
        /// </summary>
        public long OriginalSize { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 RemoteAttributes { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: DATETIME <br/>
        ///  <br/>
        /// </summary>
        public DateTime RemoteChangeTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: DATETIME <br/>
        ///  <br/>
        /// </summary>
        public DateTime RemoteCreationTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: DATETIME <br/>
        ///  <br/>
        /// </summary>
        public DateTime RemoteLastAccessTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: DATETIME <br/>
        ///  <br/>
        /// </summary>
        public DateTime RemoteLastWriteTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: sint64 <br/>
        ///  <br/>
        /// </summary>
        public long RemoteSize { get; set; }
    }

    /// <summary>
    ///  <br/>
    /// provider: Win32_OfflineFilesProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesSuspendInfo
    {
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Suspended { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean SuspendedRoot { get; set; }
    }

    /// <summary>
    /// Since software elements in a ready to run state cannot transition into  another state, the value of the phase property is restricted to  in-state for CIM_SoftwareElement objects in a ready to run state. <br/>
    ///  <br/>
    /// provider: MSIProv <br/>
    ///  <br/>
    /// uuid: {3A20796C-DB33-11d2-85FC-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_ODBCDriverSoftwareElement
    {
        /// <summary>
        /// The Phase property indicates whether the referenced check is an  in-state check or a next-state check. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 Phase { get; set; }
    }

    /// <summary>
    ///  <br/>
    /// provider: Win32_OfflineFilesConfigurationProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesMachineConfiguration
    {
        /// <summary>
        /// If true, background synchronization is enabled <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean BackgroundSyncEnabled { get; set; }
        /// <summary>
        /// the background synchronization parameters. <br/>
        ///  <br/>
        /// cimtype: object:Win32_OfflineFilesBackgroundSync <br/>
        ///  <br/>
        /// </summary>
        public Object BackgroundSyncParams { get; set; }
        /// <summary>
        /// If true, the disk space used by offline files is limited <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean DiskSpaceLimitEnabled { get; set; }
        /// <summary>
        /// This object&apos;s properties determine how the disk space is managed. <br/>
        ///  <br/>
        /// cimtype: object:Win32_OfflineFilesDiskSpaceLimit <br/>
        ///  <br/>
        /// </summary>
        public Object DiskSpaceLimitParams { get; set; }
        /// <summary>
        /// If true, only administratively assigned offline files are synchronized when the user logs on. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean EconomicalAdminPinningEnabled { get; set; }
        /// <summary>
        /// If true, the Offline Files feature is enabled through a policy setting. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Enabled { get; set; }
        /// <summary>
        /// Array strings that specify the types of files that are excluded from being cached <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String[] ExcludedFileTypes { get; set; }
        /// <summary>
        /// Indicate if the configuration settings are taking affect <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean IsConfiguredByWMI { get; set; }
        /// <summary>
        /// If true, the Make Available Offline button is removed. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean MakeAvailableOfflineButtonRemoved { get; set; }
        /// <summary>
        /// If true, the Offline Files cache will be encrypted. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean OfflineFilesCacheEncrypted { get; set; }
        /// <summary>
        /// If true, slow-link mode is enabled as specified in the SlowLinkParams property. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean SlowLinkEnabled { get; set; }
        /// <summary>
        /// An array of strings that contain the slow-link mode parameters. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String[] SlowLinkParams { get; set; }
        /// <summary>
        /// Allow syncing to occur on a costed network where the user is charged by usage. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean SyncOnCostedNetworkEnabled { get; set; }
        /// <summary>
        /// The transparent caching latency, in milliseconds. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 TransparentCachingLatencyThreshold { get; set; }
        /// <summary>
        /// If true, the Work Offline button is removed. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean WorkOfflineButtonRemoved { get; set; }
    }

    /// <summary>
    ///  <br/>
    /// provider: Win32_OfflineFilesProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesCache
    {
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Active { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Enabled { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Location { get; set; }
    }

    /// <summary>
    /// The Win32_OperatingSystemQFE class represents an association between an operating system and product updates applied as represented in Win32_QuickFixEngineering. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {2CB2C452-C516-11D2-B364-00105A1F77A1} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OperatingSystemQFE
    {
    }

    /// <summary>
    ///  <br/>
    /// provider: Win32_OfflineFilesProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesConnectionInfo
    {
        /// <summary>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ConnectState { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 OfflineReason { get; set; }
    }

    /// <summary>
    ///  <br/>
    /// provider: Win32_OfflineFilesConfigurationProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesDiskSpaceLimit
    {
        /// <summary>
        /// The maximum total size, in megabytes (MB), of all files that reside on network shares and are marked to be cached automatically, that can be cached by the Offline Files feature. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 AutoCacheSizeInMB { get; set; }
        /// <summary>
        /// The total amount of disk space, in megabytes (MB), that can be used by the Offline Files feature. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 TotalSizeInMB { get; set; }
    }

    /// <summary>
    ///  <br/>
    /// provider: Win32_OfflineFilesProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesDirtyInfo
    {
        /// <summary>
        ///  <br/>
        /// cimtype: sint64 <br/>
        ///  <br/>
        /// </summary>
        public long LocalDirtyByteCount { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: sint64 <br/>
        ///  <br/>
        /// </summary>
        public long RemoteDirtyByteCount { get; set; }
    }

    /// <summary>
    /// Private Interface <br/>
    ///  <br/>
    /// provider: UserProfileConfigurationProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_OfflineFilesHealth
    {
        /// <summary>
        /// A DATETIME value, in string format, that represents the last time this folder was successfully synchronized to the Offline Files cache. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String LastSuccessfulSyncTime { get; set; }
        /// <summary>
        /// The status of the last attempt to synchronize this folder to the Offline Files cache. <br/>
        ///  <br/>
        /// cimtype: uint8 <br/>
        ///  <br/>
        /// </summary>
        public byte LastSyncStatus { get; set; }
        /// <summary>
        /// A DATETIME value, in string format, that represents the last time an attempt was made to synchronized this folder to the Offline Files cache, even if it was unsuccessful. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String LastSyncTime { get; set; }
        /// <summary>
        /// If true, the Offline Files feature is enabled for this folder. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean OfflineAccessEnabled { get; set; }
        /// <summary>
        /// If true, the share is working in Online mode <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean OnlineMode { get; set; }
    }
}
