// <auto-generated />

using System;

namespace CIMV2
{
    /// <summary>
    /// The LaunchCondition class is used by the LaunchConditions action. <br/>
    /// It contains a list of conditions, all of which must be satisfied for the action to succeed. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: MSIProv <br/>
    ///  <br/>
    /// uuid: {E79C9694-DB32-11d2-85FC-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LaunchCondition
    {
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// An identifier used in conjunction with other keys to uniquely identify the check <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CheckID { get; set; }
        /// <summary>
        /// The CheckMode property is used to indicate whether the condition is  expected to exist or not exist in the environment. <br/>
        /// When the value is True, the condition is expected to exist  (e.g., a file is expected to be on a system) so invoke() is expected to  return True. <br/>
        /// When the value is False, the condition is not expect to exist  (e.g., a file is not to be on a system) so invoke is expected to return false <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean CheckMode { get; set; }
        /// <summary>
        /// A condition that must evaluate to TRUE for installation to begin. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Condition { get; set; }
        /// <summary>
        /// A description of the objects. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The name used to identify this software element <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.Name <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// This is an identifier for this software element. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementID <br/>
        ///  <br/>
        /// </summary>
        public String SoftwareElementID { get; set; }
        /// <summary>
        /// The software element state of a software element <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementState <br/>
        ///  <br/>
        /// </summary>
        public UInt16 SoftwareElementState { get; set; }
        /// <summary>
        /// The target operating system of the this software element. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.TargetOperatingSystem <br/>
        ///  <br/>
        /// </summary>
        public UInt16 TargetOperatingSystem { get; set; }
        /// <summary>
        /// Version should be in the form &lt;Major&gt;.&lt;Minor&gt;.&lt;Revision&gt; or &lt;Major&gt;.&lt;Minor&gt;&lt;letter&gt;&lt;revision&gt; <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.Version <br/>
        ///  <br/>
        /// </summary>
        public String Version { get; set; }
    }

    /// <summary>
    /// The Win32_LoadOrderGroup class represents a group of system services that define execution dependencies. <br/>
    /// The services must be initiated in the order specified by the Load Order Group, as the services are dependent on each other. <br/>
    /// These dependent services require the presence of the antecedent services in order to function correctly. <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {8502C4D4-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LoadOrderGroup
    {
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The DriverEnabled property indicates whether this load order group can include drivers along with system services. <br/>
        /// Values:  TRUE or FALSE. <br/>
        /// If TRUE, the load order group can includedrivers. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean DriverEnabled { get; set; }
        /// <summary>
        /// The GroupOrder property indicates the sequence in which this group of services will be loaded onto the operating system. <br/>
        /// Example: 2 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 GroupOrder { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// The Name property indicates the name of the load order group. <br/>
        /// Example: Primary disk <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: Name <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
    }

    /// <summary>
    /// The Win32_LoadOrderGroupServiceDependencies class represents an association between a base service and a load order group that the service depends on to start running. <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {8502C4FC-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LoadOrderGroupServiceDependencies
    {
    }

    /// <summary>
    /// The Win32_LoadOrderGroupServiceMembers class represents an association between a load order group and a base service. <br/>
    /// Note: Win32_SystemDriver objects are members of that load order group. <br/>
    /// Not all services are members of groups, and not all groups have services within them. <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {8502C4EF-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LoadOrderGroupServiceMembers
    {
    }

    /// <summary>
    /// Describes an instance in time as returned by Win32ClockProvider. <br/>
    /// When a query is submitted to the Win32LocalClockProvider, the results are returned as Win32_LocalTime objects with times matching the query. <br/>
    /// These are returned as part of __InstanceModificationEvents <br/>
    ///  <br/>
    /// provider: Win32ClockProvider <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LocalTime
    {
        /// <summary>
        /// The current matching day (1-31) <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Day { get; set; }
        /// <summary>
        /// The current matching day of the current week (0-6, Sunday being 0) <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 DayOfWeek { get; set; }
        /// <summary>
        /// The current hour of the current day (0-23) <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Hour { get; set; }
        /// <summary>
        /// (currently not used) <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Milliseconds { get; set; }
        /// <summary>
        /// The current minute (0-59) <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Minute { get; set; }
        /// <summary>
        /// The current matching month (1-12) <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Month { get; set; }
        /// <summary>
        /// The current quarter of the current year (1-4) <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Quarter { get; set; }
        /// <summary>
        /// The current second of the current minute (0-59) <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Second { get; set; }
        /// <summary>
        /// The current week in the current month (1-6) <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 WeekInMonth { get; set; }
        /// <summary>
        /// The current matching year (4 digits) <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Year { get; set; }
    }

    /// <summary>
    /// The Win32_LoggedOnUser association represents the relationship between a session and the user account using that session. <br/>
    /// Although the association will usually be one to one - users are possible that involve more than one session. <br/>
    /// At the termination of the session the association instance is deleted. <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {8BB5B3EC-E1F7-4b39-942A-605D5F55789A} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LoggedOnUser
    {
    }

    /// <summary>
    /// The Win32_LogicalDisk class represents a data source that resolves to an actual local storage device on a Win32 system. <br/>
    /// The class returns both local as well as mapped logical disks. <br/>
    /// However, the recommended approach is to use this class for obtaining information on local disks and to use the Win32_MappedLogicalDisk class for information on mapped logical disk. <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {8502C4B7-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalDisk
    {
        /// <summary>
        /// Access describes whether the media is readable (value=1), writeable (value=2), or both (value=3). <br/>
        /// &quot;Unknown&quot; (0) and &quot;Write Once&quot; (4) can also be defined. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 Access { get; set; }
        /// <summary>
        /// The availability and status of the device. <br/>
        /// For example, the Availability property indicates that the device is running and has full power (value=3), or is in a warning (4), test (5), degraded (10) or power save state (values 13-15 and 17). <br/>
        /// Regarding the power saving states, these are defined as follows: Value 13 (&quot;Power Save - Unknown&quot;) indicates that the device is known to be in a power save mode, but its exact status in this mode is unknown; 14 (&quot;Power Save - Low Power Mode&quot;) indicates that the device is in a power save state but still functioning, and may exhibit degraded performance; 15 (&quot;Power Save - Standby&quot;) describes that the device is not functioning but could be brought to full power &apos;quickly&apos;; and value 17 (&quot;Power Save - Warning&quot;) indicates that the device is in a warning state, though also in a power save mode. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 Availability { get; set; }
        /// <summary>
        /// Size in bytes of the blocks which form this StorageExtent. <br/>
        /// If variable block size, then the maximum block size in bytes should be specified. <br/>
        /// If the block size is unknown or if a block concept is not valid (for example, for Aggregate Extents, Memory or LogicalDisks), enter a 1. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: bytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 BlockSize { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// The Compressed property indicates whether the logical volume exists as a single compressed entity, such as a DoubleSpace volume. <br/>
        /// If file based compression is supported (such as on NTFS), this property will be FALSE. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Compressed { get; set; }
        /// <summary>
        /// Indicates the Win32 Configuration Manager error code. <br/>
        /// The following values may be returned: <br/>
        /// 0      This device is working properly. <br/>
        /// 1      This device is not configured correctly. <br/>
        /// 2      Windows cannot load the driver for this device. <br/>
        /// 3      The driver for this device might be corrupted, or your system may be running low on memory or other resources. <br/>
        /// 4      This device is not working properly. <br/>
        /// One of its drivers or your registry might be corrupted. <br/>
        /// 5      The driver for this device needs a resource that Windows cannot manage. <br/>
        /// 6      The boot configuration for this device conflicts with other devices. <br/>
        /// 7      Cannot filter. <br/>
        /// 8      The driver loader for the device is missing. <br/>
        /// 9      This device is not working properly because the controlling firmware is reporting the resources for the device incorrectly. <br/>
        /// 10     This device cannot start. <br/>
        /// 11     This device failed. <br/>
        /// 12     This device cannot find enough free resources that it can use. <br/>
        /// 13     Windows cannot verify this device&apos;s resources. <br/>
        /// 14     This device cannot work properly until you restart your computer. <br/>
        /// 15     This device is not working properly because there is probably a re-enumeration problem. <br/>
        /// 16     Windows cannot identify all the resources this device uses. <br/>
        /// 17     This device is asking for an unknown resource type. <br/>
        /// 18     Reinstall the drivers for this device. <br/>
        /// 19     Your registry might be corrupted. <br/>
        /// 20     Failure using the VxD loader. <br/>
        /// 21     System failure: Try changing the driver for this device. <br/>
        /// If that does not work, see your hardware documentation. <br/>
        /// Windows is removing this device. <br/>
        /// 22     This device is disabled. <br/>
        /// 23     System failure: Try changing the driver for this device. <br/>
        /// If that doesn&apos;t work, see your hardware documentation. <br/>
        /// 24     This device is not present, is not working properly, or does not have all its drivers installed. <br/>
        /// 25     Windows is still setting up this device. <br/>
        /// 26     Windows is still setting up this device. <br/>
        /// 27     This device does not have valid log configuration. <br/>
        /// 28     The drivers for this device are not installed. <br/>
        /// 29     This device is disabled because the firmware of the device did not give it the required resources. <br/>
        /// 30     This device is using an Interrupt Request (IRQ) resource that another device is using. <br/>
        /// 31     This device is not working properly because Windows cannot load the drivers required for this device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ConfigManagerErrorCode { get; set; }
        /// <summary>
        /// Indicates whether the device is using a user-defined configuration. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ConfigManagerUserConfig { get; set; }
        /// <summary>
        /// CreationClassName indicates the name of the class or the subclass used in the creation of an instance. <br/>
        /// When used with the other key properties of this class, this property allows all instances of this class and its subclasses to be uniquely identified. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CreationClassName { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The DeviceID property contains a string uniquely identifying the logical disk from other devices on the system. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: DeviceId <br/>
        ///  <br/>
        /// </summary>
        public String DeviceID { get; set; }
        /// <summary>
        /// The DriveType property contains a numeric value corresponding to the type of disk drive this logical disk represents. <br/>
        /// Please refer to the Platform SDK documentation for additional values. <br/>
        /// Example: A CD-ROM drive would return 5. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 DriveType { get; set; }
        /// <summary>
        /// ErrorCleared is a boolean property indicating that the error reported in LastErrorCode property is now cleared. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ErrorCleared { get; set; }
        /// <summary>
        /// ErrorDescription is a free-form string supplying more information about the error recorded in LastErrorCode property, and information on any corrective actions that may be taken. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ErrorDescription { get; set; }
        /// <summary>
        /// ErrorMethodology is a free-form string describing the type of error detection and correction supported by this storage extent. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ErrorMethodology { get; set; }
        /// <summary>
        /// The FileSystem property indicates the file system on the logical disk. <br/>
        /// Example: NTFS <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String FileSystem { get; set; }
        /// <summary>
        /// The FreeSpace property indicates in bytes how much free space is available on the logical disk. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: bytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 FreeSpace { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// LastErrorCode captures the last error code reported by the logical device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 LastErrorCode { get; set; }
        /// <summary>
        /// The MaximumComponentLength property contains the maximum length of a filename component supported by the Win32 drive. <br/>
        /// A filename component is that portion of a filename between backslashes. <br/>
        /// The value can be used to indicate that long names are supported by the specified file system. <br/>
        /// For example, for a FAT file system supporting long names, the function stores the value 255, rather than the previous 8.3 indicator. <br/>
        /// Long names can also be supported on systems that use the NTFS file system. <br/>
        /// Example: 255 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 MaximumComponentLength { get; set; }
        /// <summary>
        /// The MediaType property indicates the type of media currently present in the logical drive. <br/>
        /// This value will be one of the values of the MEDIA_TYPE enumeration defined in winioctl.h. <br/>
        /// &lt;B&gt;Note:&lt;/B&gt; The value may not be exact for removable drives if currently there is no media in the drive. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 MediaType { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// Total number of consecutive blocks, each block the size of the value contained in the BlockSize property, which form this storage extent. <br/>
        /// Total size of the storage extent can be calculated by multiplying the value of the BlockSize property by the value of this property. <br/>
        /// If the value of BlockSize is 1, this property is the total size of the storage extent. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 NumberOfBlocks { get; set; }
        /// <summary>
        /// Indicates the Win32 Plug and Play device ID of the logical device. <br/>
        /// Example: *PNP030b <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String PNPDeviceID { get; set; }
        /// <summary>
        /// Indicates the specific power-related capabilities of the logical device. <br/>
        /// The array values, 0=&quot;Unknown&quot;, 1=&quot;Not Supported&quot; and 2=&quot;Disabled&quot; are self-explanatory. <br/>
        /// The value, 3=&quot;Enabled&quot; indicates that the power management features are currently enabled but the exact feature set is unknown or the information is unavailable. <br/>
        /// &quot;Power Saving Modes Entered Automatically&quot; (4) describes that a device can change its power state based on usage or other criteria. <br/>
        /// &quot;Power State Settable&quot; (5) indicates that the SetPowerState method is supported. <br/>
        /// &quot;Power Cycling Supported&quot; (6) indicates that the SetPowerState method can be invoked with the PowerState input variable set to 5 (&quot;Power Cycle&quot;). <br/>
        /// &quot;Timed Power On Supported&quot; (7) indicates that the SetPowerState method can be invoked with the PowerState input variable set to 5 (&quot;Power Cycle&quot;) and the Time parameter set to a specific date and time, or interval, for power-on. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16[] PowerManagementCapabilities { get; set; }
        /// <summary>
        /// Boolean indicating that the Device can be power managed - ie, put into a power save state. <br/>
        /// This boolean does not indicate that power management features are currently enabled, or if enabled, what features are supported. <br/>
        /// Refer to the PowerManagementCapabilities array for this information. <br/>
        /// If this boolean is false, the integer value 1, for the string, &quot;Not Supported&quot;, should be the only entry in the PowerManagementCapabilities array. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean PowerManagementSupported { get; set; }
        /// <summary>
        /// The ProviderName property indicates the network path name to the logical device. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ProviderName { get; set; }
        /// <summary>
        /// A free form string describing the media and/or its use. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Purpose { get; set; }
        /// <summary>
        /// The QuotasDisabled property indicates that Quota management is not enabled on this volume. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean QuotasDisabled { get; set; }
        /// <summary>
        /// The QuotasIncomplete property indicates that Quota management was used but has been disabled. <br/>
        /// Incomplete refers to the information left in the file system  after quota management has been disabled. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean QuotasIncomplete { get; set; }
        /// <summary>
        /// The QuotasRebuilding property indicates an active state signifying that the file system is in process of compiling information and setting the disk up for quota management. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean QuotasRebuilding { get; set; }
        /// <summary>
        /// The Size property indicates in bytes, the size of the logical disk. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: bytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 Size { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// StatusInfo is a string indicating whether the logical device is in an enabled (value = 3), disabled (value = 4) or some other (1) or unknown (2) state. <br/>
        /// If this property does not apply to the logical device, the value, 5 (&quot;Not Applicable&quot;), should be used. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 StatusInfo { get; set; }
        /// <summary>
        /// The SupportsDiskQuotas property indicates whether this volume supports disk Quotas <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean SupportsDiskQuotas { get; set; }
        /// <summary>
        /// The SupportsFileBasedCompression property indicates whether the logical disk partition supports file based compression, such as is the case with NTFS. <br/>
        /// This property is FALSE, when the Compressed property is TRUE. <br/>
        /// Values: TRUE or FALSE. <br/>
        /// If TRUE, the logical disk supports file based compression. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean SupportsFileBasedCompression { get; set; }
        /// <summary>
        /// The scoping System&apos;s CreationClassName. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.CreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String SystemCreationClassName { get; set; }
        /// <summary>
        /// The scoping System&apos;s Name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.Name <br/>
        ///  <br/>
        /// </summary>
        public String SystemName { get; set; }
        /// <summary>
        /// The VolumeDirty property indicates whether the disk requires chkdsk to be run at next boot up time. <br/>
        /// The property is applicable to only those instances of logical disk that represent a physical disk in the machine. <br/>
        /// It is not applicable to mapped logical drives. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean VolumeDirty { get; set; }
        /// <summary>
        /// The VolumeName property indicates the volume name of the logical disk. <br/>
        /// Constraints: Maximum 32 characters <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String VolumeName { get; set; }
        /// <summary>
        /// The VolumeSerialNumber property indicates the volume serial number of the logical disk. <br/>
        /// Constraints: Maximum 11 characters <br/>
        /// Example: A8C3-D032 <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String VolumeSerialNumber { get; set; }
    }

    /// <summary>
    /// The Win32_LogicalDiskRootDirectory class represents an association between a logical disk and its directory structure. <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {F25FE468-783E-11d2-90BF-0060081A46FD} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalDiskRootDirectory
    {
    }

    /// <summary>
    /// The Win32_LogicalDiskToPartition class represents an association between a logical disk drive and the disk partition it resides on. <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {8502C4FB-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalDiskToPartition
    {
        /// <summary>
        /// EndingAddress indicates where in lower level storage, the higher level extent ends. <br/>
        /// This property is useful when mapping non-contiguous extents into a higher level grouping. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 EndingAddress { get; set; }
        /// <summary>
        /// StartingAddress indicates where in lower level storage, the higher level extent begins. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 StartingAddress { get; set; }
    }

    /// <summary>
    /// Association between the security settings of a file/directory and one member of its DACL <br/>
    ///  <br/>
    /// provider: SECRCW32 <br/>
    ///  <br/>
    /// uuid: {8502C590-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalFileAccess
    {
        /// <summary>
        /// Bit flags specifying what permissions are affected <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 AccessMask { get; set; }
        /// <summary>
        /// The guid of the type of object this object inherits from <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String GuidInheritedObjectType { get; set; }
        /// <summary>
        /// The guid of the type of object the security settings are applied to <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String GuidObjectType { get; set; }
        /// <summary>
        /// Bit flags specifying how the access rights are inherited <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Inheritance { get; set; }
        /// <summary>
        /// The type of access specified for the trustee <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Type { get; set; }
    }

    /// <summary>
    /// Association between the security settings of a file/directory one member of its SACL. <br/>
    ///  <br/>
    /// provider: SECRCW32 <br/>
    ///  <br/>
    /// uuid: {FCC86599-DB20-11d2-85FC-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalFileAuditing
    {
        /// <summary>
        /// Bit flags specifying what activities are audited <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 AuditedAccessMask { get; set; }
        /// <summary>
        /// The guid of the type of object this object inherits from <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String GuidInheritedObjectType { get; set; }
        /// <summary>
        /// The guid of the type of object the security settings are applied to <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String GuidObjectType { get; set; }
        /// <summary>
        /// Bit flags specifying how the audit policies are inherited <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Inheritance { get; set; }
        /// <summary>
        /// The type of access specified for the trustee <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Type { get; set; }
    }

    /// <summary>
    /// Association between the security settings of a file/directory and its group <br/>
    ///  <br/>
    /// provider: SECRCW32 <br/>
    ///  <br/>
    /// uuid: {8502C58F-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalFileGroup
    {
    }

    /// <summary>
    /// Association between the security settings of a file/directory and its owner <br/>
    ///  <br/>
    /// provider: SECRCW32 <br/>
    ///  <br/>
    /// uuid: {8502C58E-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalFileOwner
    {
    }

    /// <summary>
    /// security settings for a logical file <br/>
    ///  <br/>
    /// provider: SECRCW32 <br/>
    ///  <br/>
    /// uuid: {8502C58C-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalFileSecuritySetting
    {
        /// <summary>
        /// A short textual description (one-line string) of the CIM_Setting object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// Inheritance-related flags. <br/>
        /// See SECURITY_DESCRIPTOR_CONTROL <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ControlFlags { get; set; }
        /// <summary>
        /// A textual description of the CIM_Setting object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// Indicates whether the caller has Owner permissions to the object. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean OwnerPermissions { get; set; }
        /// <summary>
        /// The full pathname of the file or directory <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Path { get; set; }
        /// <summary>
        /// The identifier by which the CIM_Setting object is known. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SettingID { get; set; }
    }

    /// <summary>
    /// The Win32_LogicalProgramGroup class represents a program group in a Win32 system. <br/>
    /// Example: Accessories or Startup. <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {D52706F2-8045-11d2-90CE-0060081A46FD} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalProgramGroup
    {
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The GroupName property indicates the name of the Win32 program group. <br/>
        /// Program groups are implemented as file folders in Win32. <br/>
        /// Example: Accessories\System Tools <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String GroupName { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// The Name property indicates the user assigned name followed by the group name. <br/>
        /// Program groups are implemented as file folders in Win32. <br/>
        /// Example: All Users:Accessories\System Tools <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: Name <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// The UserName property indicates the users who can access the Win32 program group. <br/>
        /// Program groups are implemented as file folders in Win32. <br/>
        /// Example: All Users <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String UserName { get; set; }
    }

    /// <summary>
    /// The Win32_LogicalProgramGroupDirectory class represents an association between logical program groups (groupings in the start menu) and the file directories in which they are stored. <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {F25FE467-783E-11d2-90BF-0060081A46FD} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalProgramGroupDirectory
    {
    }

    /// <summary>
    /// The Win32_LogicalProgramGroupItem class represents an element contained by a Win32_ProgramGroup, that is not itself another Win32_ProgramGroup. <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {86E30E82-7DB2-11d2-90CB-0060081A46FD} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalProgramGroupItem
    {
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// The inherited Name property serves as key of a Win32_LogicalProgramGroupItem instance within a computer system. <br/>
        /// Program Groups are implemented as file folders in Win32. <br/>
        /// Full path names should be provided. <br/>
        /// Example: f:\WINNT\Profiles\a-kevhu.000\ Start Menu\Programs\Accessories\WordPad.Lnk <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: Name <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
    }

    /// <summary>
    /// The Win32_LogicalProgramGroupItemDataFile class represents an association between the program group items of the start menu and the files in which they are stored. <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {08FFAD62-8050-11d2-90CE-0060081A46FD} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalProgramGroupItemDataFile
    {
    }

    /// <summary>
    /// Association between the security settings of a share and one member of its DACL <br/>
    ///  <br/>
    /// provider: SECRCW32 <br/>
    ///  <br/>
    /// uuid: {8502C593-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalShareAccess
    {
        /// <summary>
        /// Bit flags specifying what permissions are affected <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 AccessMask { get; set; }
        /// <summary>
        /// The guid of the type of object this object inherits from <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String GuidInheritedObjectType { get; set; }
        /// <summary>
        /// The guid of the type of object the security settings are applied to <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String GuidObjectType { get; set; }
        /// <summary>
        /// Bit flags specifying how the access rights are inherited <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Inheritance { get; set; }
        /// <summary>
        /// The type of access specified for the trustee <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Type { get; set; }
    }

    /// <summary>
    /// Association between the security settings of a share and one member of its SACL. <br/>
    ///  <br/>
    /// provider: SECRCW32 <br/>
    ///  <br/>
    /// uuid: {8502C594-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalShareAuditing
    {
        /// <summary>
        /// Bit flags specifying what activities are audited <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 AuditedAccessMask { get; set; }
        /// <summary>
        /// The guid of the type of object this object inherits from <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String GuidInheritedObjectType { get; set; }
        /// <summary>
        /// The guid of the type of object the security settings are applied to <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String GuidObjectType { get; set; }
        /// <summary>
        /// Bit flags specifying how the audit policies are inherited <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Inheritance { get; set; }
        /// <summary>
        /// The type of access specified for the trustee <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Type { get; set; }
    }

    /// <summary>
    /// security settings for a logical file <br/>
    ///  <br/>
    /// provider: SECRCW32 <br/>
    ///  <br/>
    /// uuid: {8502C591-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogicalShareSecuritySetting
    {
        /// <summary>
        /// A short textual description (one-line string) of the CIM_Setting object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// Inheritance-related flags. <br/>
        /// See SECURITY_DESCRIPTOR_CONTROL <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ControlFlags { get; set; }
        /// <summary>
        /// A textual description of the CIM_Setting object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The name of the share <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The identifier by which the CIM_Setting object is known. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SettingID { get; set; }
    }

    /// <summary>
    /// The Win32_LogonSession class describes the logon session or sessions associated with a user who has logged on to Windows NT or Windows 2000. <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {9083C21E-7D58-4e0e-BC30-0BC8922AFB8B} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogonSession
    {
        /// <summary>
        /// The AuthenticationPackage is the name of the subsystem used to authenticate the logon session. <br/>
        ///  <br/>
        /// cimtype: String <br/>
        ///  <br/>
        /// </summary>
        public String AuthenticationPackage { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// The LogonId is the ID assigned to the logon session. <br/>
        /// The application that initiated the session should have called AllocateLocallyUniqueId in order to generate this ID. <br/>
        ///  <br/>
        /// cimtype: String <br/>
        ///  <br/>
        /// </summary>
        public String LogonId { get; set; }
        /// <summary>
        /// The LogonType is a numeric value indicating what type of logon session this is. <br/>
        /// System - Interactive - This logon type is intended for users who will be interactively using the machine, such as a user being logged on by a terminal server, remote shell, or similar process. <br/>
        /// Network - This logon type is intended for high performance servers to authenticate clear text passwords. <br/>
        /// LogonUser does not cache credentials for this logon type. <br/>
        /// Batch - This logon type is intended for batch servers, where processes may be executing on behalf of a user without their direct intervention; or for higher performance servers that process many clear-text authentication attempts at a time, such as mail or web servers. <br/>
        /// LogonUser does not cache credentials for this logon type. <br/>
        /// Service - Indicates a service-type logon. <br/>
        /// The account provided must have the service privilege enabled. <br/>
        /// Proxy - Proxy logon. <br/>
        /// This logon type is not supported. <br/>
        /// Unlock - This logon type is intended for GINA DLLs logging on users who will be interactively using the machine. <br/>
        /// This logon type allows a unique audit record to be generated that shows when the workstation was unlocked. <br/>
        /// Network Cleartext - Windows 2000: This logon type preserves the name and password in the authentication packages, allowing the server to make connections to other network servers while impersonating the client. <br/>
        /// This allows a server to accept clear text credentials from a client, call LogonUser, verify that the user can access the system across the network, and still communicate with other servers. <br/>
        /// New Credentials - Windows 2000: This logon type allows the caller to clone its current token and specify new credentials for outbound connections. <br/>
        /// The new logon session has the same local identify, but uses different credentials for other network connections. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 LogonType { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The StartTime property represents the time at which the session started. <br/>
        ///  <br/>
        /// cimtype: DateTime <br/>
        ///  <br/>
        /// </summary>
        public DateTime StartTime { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
    }

    /// <summary>
    /// The Win32_LogonSessionMappedDisk class represents an association between a logon session and the mapped logical disks defined within the session. <br/>
    ///  <br/>
    /// provider: CIMWin32a <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LogonSessionMappedDisk
    {
    }

    /// <summary>
    /// The Win32_LUID abstract class represents a locally unique identifier (LUID), an identifier unique only on the local computer. <br/>
    /// Instances of the Win32_LUID class identify a process or thread so that they can be associated with security token privileges represented by instances of the Win32_LUIDandAttributes class. <br/>
    /// For more information about the role of LUIDs in security, see LUID. <br/>
    ///  <br/>
    /// uuid: {0FF18C30-FA51-11d3-9C37-006008B088CE} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LUID
    {
        /// <summary>
        /// Specifies the most significant bits of the LUID. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 HighPart { get; set; }
        /// <summary>
        /// Specifies the least significant bits of the LUID. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 LowPart { get; set; }
    }

    /// <summary>
    /// The Win32_LUIDandAttributes abstract class represents a locally unique identifier (LUID) of a privilege and a set of bit flags that indicate the attributes of the privilege, such as whether the privilege is enabled. <br/>
    /// Each LUID and attributes structure defines the availability of a security privilege for the process. <br/>
    /// For more information, see LUID_AND_ATTRIBUTES. <br/>
    ///  <br/>
    /// uuid: {63021F4B-F377-4a88-ABD1-835D14142142} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_LUIDandAttributes
    {
        /// <summary>
        /// Specifies attributes of the LUID. <br/>
        /// This value contains two 32-bit flags. <br/>
        /// Its meaning is dependent on the definition and use of the LUIDSpecifies attributes of the LUID. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Attributes { get; set; }
        /// <summary>
        /// Specifies a LUID value. <br/>
        ///  <br/>
        /// cimtype: object:Win32_LUID <br/>
        ///  <br/>
        /// </summary>
        public Object LUID { get; set; }
    }
}
