// <auto-generated />

using System;

namespace CIMV2
{
    /// <summary>
    /// The Win32_Environment class represents an environment or system environment setting on a Win32 computer system.<br/>
    /// <br/>
    /// createby: PutInstance<br/>
    /// <br/>
    /// deleteby: DeleteInstance<br/>
    /// <br/>
    /// provider: CIMWin32<br/>
    /// <br/>
    /// uuid: {8502C4D2-5FBB-11D2-AAC1-006008C78BC7}<br/>
    /// <br/>
    /// </summary>
    public class Win32_Environment
    {
        /// <summary>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// <br/>
        /// cimtype: datetime<br/>
        /// <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// The Name property contains a character string specifying the name of a Win32 environment variable.<br/>
        /// By specifying the name of a variable that does not yet exist, an application can create a new environment variable.<br/>
        /// Example: Path.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// override: Name<br/>
        /// <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// The SystemVariable property indicates whether the variable is a system variable.<br/>
        /// A system variable is set by the operating system, and is independent from user environment settings.<br/>
        /// Values: TRUE or FALSE.<br/>
        /// A value of TRUE indicates the variable is a system variable.<br/>
        /// <br/>
        /// cimtype: boolean<br/>
        /// <br/>
        /// </summary>
        public Boolean SystemVariable { get; set; }
        /// <summary>
        /// The UserName property indicates the owner of the environment setting.<br/>
        /// It is set to &quot;&lt;SYSTEM&gt;&quot; for settings that are specific to the Win32 system (as opposed to a specific user) and &quot;&lt;DEFAULT&gt;&quot; for default user settings.<br/>
        /// Example: Jsmith.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String UserName { get; set; }
        /// <summary>
        /// The VariableValue property contains the placeholder variable of a Win32 environment variable.<br/>
        /// Information like the file system directory can change from machine to machine.<br/>
        /// The operating system substitutes placeholders for these.<br/>
        /// Example: %SystemRoot%.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String VariableValue { get; set; }
    }
    
    /// <summary>
    /// Instances of this class contain information about any environment variables that may need to be registered for their associated products installation.<br/>
    /// <br/>
    /// locale: ms_409<br/>
    /// <br/>
    /// provider: MSIProv<br/>
    /// <br/>
    /// uuid: {8518ABC0-DB32-11d2-85FC-0000F8102E5F}<br/>
    /// <br/>
    /// </summary>
    public class Win32_EnvironmentSpecification
    {
        /// <summary>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// An identifier used in conjunction with other keys to uniquely identify the check<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String CheckID { get; set; }
        /// <summary>
        /// The CheckMode property is used to indicate whether the condition is  expected to exist or not exist in the environment.<br/>
        /// When the value is True, the condition is expected to exist  (e.g., a file is expected to be on a system) so invoke() is expected to  return True.<br/>
        /// When the value is False, the condition is not expect to exist  (e.g., a file is not to be on a system) so invoke is expected to return false<br/>
        /// <br/>
        /// cimtype: boolean<br/>
        /// <br/>
        /// </summary>
        public Boolean CheckMode { get; set; }
        /// <summary>
        /// A description of the objects.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// Token name for the environment specification within its package.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Environment { get; set; }
        /// <summary>
        /// The name used to identify this software element<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// propagated: CIM_SoftwareElement.Name<br/>
        /// <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// This is an identifier for this software element.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementID<br/>
        /// <br/>
        /// </summary>
        public String SoftwareElementID { get; set; }
        /// <summary>
        /// The software element state of a software element<br/>
        /// <br/>
        /// cimtype: uint16<br/>
        /// <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementState<br/>
        /// <br/>
        /// </summary>
        public UInt16 SoftwareElementState { get; set; }
        /// <summary>
        /// The target operating system of the this software element.<br/>
        /// <br/>
        /// cimtype: uint16<br/>
        /// <br/>
        /// propagated: CIM_SoftwareElement.TargetOperatingSystem<br/>
        /// <br/>
        /// </summary>
        public UInt16 TargetOperatingSystem { get; set; }
        /// <summary>
        /// The value for this environment as a formatted string.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Value { get; set; }
        /// <summary>
        /// Version should be in the form &lt;Major&gt;.&lt;Minor&gt;.&lt;Revision&gt; or &lt;Major&gt;.&lt;Minor&gt;&lt;letter&gt;&lt;revision&gt;<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// propagated: CIM_SoftwareElement.Version<br/>
        /// <br/>
        /// </summary>
        public String Version { get; set; }
    }
    
    /// <summary>
    /// The ExtensionInfoAction manages the registration of extension related information with the system.<br/>
    /// The action registers the extension servers for which the corresponding feature is currently selected to be uninstalled.<br/>
    /// <br/>
    /// locale: ms_409<br/>
    /// <br/>
    /// provider: MSIProv<br/>
    /// <br/>
    /// uuid: {9668DF4E-DB32-11d2-85FC-0000F8102E5F}<br/>
    /// <br/>
    /// </summary>
    public class Win32_ExtensionInfoAction
    {
        /// <summary>
        /// The ActionID property is a unique identifier assigned to a particular  action for a software element.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String ActionID { get; set; }
        /// <summary>
        /// Value for the command arguments.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Argument { get; set; }
        /// <summary>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// The text displayed on the context menu.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Command { get; set; }
        /// <summary>
        /// A description of the object.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The Direction property indicates whether a particular   CIM_Action object is part of a sequence of actions to transition the   current software element to its next state, such as &quot;Install&quot; or to  remove the current software element, such as &quot;Uninstall&quot;.<br/>
        /// <br/>
        /// cimtype: uint16<br/>
        /// <br/>
        /// </summary>
        public UInt16 Direction { get; set; }
        /// <summary>
        /// The extension associated with an instance.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Extension { get; set; }
        /// <summary>
        /// The MIME type associated with this extension.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String MIME { get; set; }
        /// <summary>
        /// Name is used to identify this software element<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// propagated: CIM_SoftwareElement.Name<br/>
        /// <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The Program ID associated with this extension.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String ProgID { get; set; }
        /// <summary>
        /// Parameters for shell execution.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String ShellNew { get; set; }
        /// <summary>
        /// Value for shell execution.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String ShellNewValue { get; set; }
        /// <summary>
        /// The SoftwareElementID is an identifier for this software element.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementID<br/>
        /// <br/>
        /// </summary>
        public String SoftwareElementID { get; set; }
        /// <summary>
        /// The SoftwareElementState indicates the state of a software element<br/>
        /// <br/>
        /// cimtype: uint16<br/>
        /// <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementState<br/>
        /// <br/>
        /// </summary>
        public UInt16 SoftwareElementState { get; set; }
        /// <summary>
        /// The TargetOperatingSystem indicates the target operating system of the owning software element.<br/>
        /// <br/>
        /// cimtype: uint16<br/>
        /// <br/>
        /// propagated: CIM_SoftwareElement.TargetOperatingSystem<br/>
        /// <br/>
        /// </summary>
        public UInt16 TargetOperatingSystem { get; set; }
        /// <summary>
        /// The verb for the command.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// </summary>
        public String Verb { get; set; }
        /// <summary>
        /// Version should be in the form &lt;major&gt;.&lt;minor&gt;.&lt;revision&gt; or &lt;major&gt;.&lt;minor&gt;&lt;letter&gt;&lt;revision&gt;.<br/>
        /// <br/>
        /// cimtype: string<br/>
        /// <br/>
        /// propagated: CIM_SoftwareElement.Version<br/>
        /// <br/>
        /// </summary>
        public String Version { get; set; }
    }
    
}
