// <auto-generated />

using System;

namespace CIMV2
{
    /// <summary>
    /// The ThreadTrace event class is the base event for thread events. <br/>
    ///  <br/>
    /// </summary>
    public class Win32_ThreadTrace
    {
        /// <summary>
        /// The ProcessID property contains the process identifier of the process to which the thread belongs. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ProcessID { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint8 <br/>
        ///  <br/>
        /// </summary>
        public byte[] SECURITY_DESCRIPTOR { get; set; }
        /// <summary>
        /// The ThreadID property contains the thread identifier of the thread involved in the event. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ThreadID { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 TIME_CREATED { get; set; }
    }

    /// <summary>
    /// The ThreadStartTrace event class indicates a new thread has started. <br/>
    ///  <br/>
    /// </summary>
    public class Win32_ThreadStartTrace
    {
        /// <summary>
        /// The ProcessID property contains the process identifier of the process to which the thread belongs. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ProcessID { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint8 <br/>
        ///  <br/>
        /// </summary>
        public byte[] SECURITY_DESCRIPTOR { get; set; }
        /// <summary>
        /// The StackBase property indicates the base address of the thread&apos;s stack. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 StackBase { get; set; }
        /// <summary>
        /// The StackBase property indicates the limit of the thread&apos;s stack. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 StackLimit { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 StartAddr { get; set; }
        /// <summary>
        /// The ThreadID property contains the thread identifier of the thread involved in the event. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ThreadID { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 TIME_CREATED { get; set; }
        /// <summary>
        /// The UserStackBase property indicates the base address of the thread&apos;s user-mode stack. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 UserStackBase { get; set; }
        /// <summary>
        /// The UserStackLimit property indicates the limit of the thread&apos;s user-mode stack. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 UserStackLimit { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 WaitMode { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 Win32StartAddr { get; set; }
    }

    /// <summary>
    /// The ThreadStopTrace event class indicates a thread has terminated. <br/>
    ///  <br/>
    /// </summary>
    public class Win32_ThreadStopTrace
    {
        /// <summary>
        /// The ProcessID property contains the process identifier of the process to which the thread belongs. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ProcessID { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint8 <br/>
        ///  <br/>
        /// </summary>
        public byte[] SECURITY_DESCRIPTOR { get; set; }
        /// <summary>
        /// The ThreadID property contains the thread identifier of the thread involved in the event. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ThreadID { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 TIME_CREATED { get; set; }
    }

    /// <summary>
    /// The Win32_TerminalService class provides Terminal Service load balancing indicators. <br/>
    ///  <br/>
    /// classcontext: local|hkey_local_machine\SYSTEM\CurrentControlSet\Control\TerminalServer <br/>
    ///  <br/>
    /// provider: Win32_WIN32_TERMINALSERVICE_Prov <br/>
    ///  <br/>
    /// </summary>
    public class Win32_TerminalService
    {
        /// <summary>
        /// The AcceptPause property indicates whether the service can be paused. <br/>
        /// Values: TRUE or FALSE. <br/>
        /// A value of TRUE indicates the service can be paused. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean AcceptPause { get; set; }
        /// <summary>
        /// The AcceptStop property indicates whether the service can be stopped. <br/>
        /// Values: TRUE or FALSE. <br/>
        /// A value of TRUE indicates the service can be stopped. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean AcceptStop { get; set; }
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// The CheckPoint property specifies a value that the service increments periodically to report its progress during a lengthy start, stop, pause, or continue operation. <br/>
        /// For example, the service should increment this value as it completes each step of its initialization when it is starting up. <br/>
        /// The user interface program that invoked the operation on the service uses this value to track the progress of the service during a lengthy operation. <br/>
        /// This value is not valid and should be zero when the service does not have a start, stop, pause, or continue operation pending. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 CheckPoint { get; set; }
        /// <summary>
        /// CreationClassName indicates the name of the class or the subclass used in the creation of an instance. <br/>
        /// When used with the other key properties of this class, this property allows all instances of this class and its subclasses to be uniquely identified. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CreationClassName { get; set; }
        /// <summary>
        /// The DelayedAutoStart property specifies if the service is started after other auto-start services are started plus a short delay. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean DelayedAutoStart { get; set; }
        /// <summary>
        /// The Description property provides a textual description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The DesktopInteract property indicates whether the service can create or communicate with windows on the desktop. <br/>
        /// Values: TRUE or FALSE. <br/>
        /// A value of TRUE indicates the service can create or communicate with windows on the desktop. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean DesktopInteract { get; set; }
        /// <summary>
        /// The number of disconnected sessions on this server. <br/>
        /// These sessions may still be actively consuming server resources, however they currently have no network. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 DisconnectedSessions { get; set; }
        /// <summary>
        /// The DisplayName property indicates the display name of the service. <br/>
        /// This string has a maximum length of 256 characters. <br/>
        /// The name is case-preserved in the Service Control Manager. <br/>
        /// DisplayName comparisons are always case-insensitive. <br/>
        /// Constraints: Accepts the same value as the Name property. <br/>
        /// Example: Atdisk. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String DisplayName { get; set; }
        /// <summary>
        /// If this service fails to start during startup, the ErrorControl property specifies the severity of the error. <br/>
        /// The value indicates the action taken by the startup program if failure occurs. <br/>
        /// All errors are logged by the computer system. <br/>
        /// The computer system does not notify the user of &quot;Ignore&quot; errors. <br/>
        /// With &quot;Normal&quot; errors the user is notified. <br/>
        /// With &quot;Severe&quot; errors, the system is restarted with the last-known-good configuration. <br/>
        /// Finally, on&quot;Critical&quot; errors the system attempts to restart with a good configuration. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ErrorControl { get; set; }
        /// <summary>
        /// The ExitCode property specifies a Win32 error code defining any problems encountered in starting or stopping the service. <br/>
        /// This property is set to ERROR_SERVICE_SPECIFIC_ERROR (1066) when the error is unique to the service represented by this class, and information about the error is available in the ServiceSpecificExitCode member. <br/>
        /// The service sets this value to NO_ERROR when running, and again upon normal termination. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ExitCode { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// The Name property uniquely identifies the service and provides an indication of the functionality that is managed. <br/>
        /// This functionality is described in more detail in the object&apos;s Description property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The PathName property contains the fully qualified path to the service binary file that implements the service. <br/>
        /// Example: \SystemRoot\System32\drivers\afd.sys <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String PathName { get; set; }
        /// <summary>
        /// The ProcessId property specifies the process identifier of the service. <br/>
        /// Example: 324 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ProcessId { get; set; }
        /// <summary>
        /// The ServiceSpecificExitCode property specifies a service-specific error code for errors that occur while the service is either starting or stopping. <br/>
        /// The exit codes are defined by the service represented by this class. <br/>
        /// This value is only set when the ExitCodeproperty value is ERROR_SERVICE_SPECIFIC_ERROR, 1066. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ServiceSpecificExitCode { get; set; }
        /// <summary>
        /// The ServiceType property supplies the type of service provided to calling processes. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ServiceType { get; set; }
        /// <summary>
        /// Started is a boolean indicating whether the service has been started (TRUE), or stopped (FALSE). <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Started { get; set; }
        /// <summary>
        /// The StartMode property indicates the start mode of the Win32 base service. <br/>
        /// &quot;Boot&quot; specifies a device driver started by the operating system loader. <br/>
        /// This value is valid only for driver services. <br/>
        /// &quot;System&quot; specifies a device driver started by the IoInitSystem function. <br/>
        /// This value is valid only for driver services. <br/>
        /// &quot;Automatic&quot; specifies a service to be started automatically by the service control manager during system startup. <br/>
        /// &quot;Manual&quot; specifies a service to be started by the service control manager when a process calls the StartService function. <br/>
        /// &quot;Disabled&quot; specifies a service that can no longer be started. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: StartMode <br/>
        ///  <br/>
        /// </summary>
        public String StartMode { get; set; }
        /// <summary>
        /// The StartName property indicates the account name under which the service runs. <br/>
        /// Depending on the service type, the account name may be in the form of &quot;DomainName\Username&quot;. <br/>
        /// The service process will be logged using one of these two forms when it runs. <br/>
        /// If the account belongs to the built-in domain, &quot;.\Username&quot; can be specified. <br/>
        /// If NULL is specified, the service will be logged on as the LocalSystem account. <br/>
        /// For kernel or system level drivers, StartName contains the driver object name (that is, \FileSystem\Rdr or \Driver\Xns) which the input and output (I/O) system uses to load the device driver. <br/>
        /// Additionally, if NULL is specified, the driver runs with a default object name created by the I/O system based on the service name. <br/>
        /// Example: DWDOM\Admin. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String StartName { get; set; }
        /// <summary>
        /// The State property indicates the current state of the base service. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String State { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// The scoping System&apos;s CreationClassName. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.CreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String SystemCreationClassName { get; set; }
        /// <summary>
        /// The name of the system that hosts this service <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.Name <br/>
        ///  <br/>
        /// </summary>
        public String SystemName { get; set; }
        /// <summary>
        /// The TagId property specifies a unique tag value for this service in the group. <br/>
        /// A value of 0 indicates that the service has not been assigned a tag. <br/>
        /// A tag can be used for ordering service startup within a load order group by specifying a tag order vector in the registry located at: HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\GroupOrderList. <br/>
        /// Tags are only evaluated for Kernel Driver and File System Driver start type services that have &quot;Boot&quot; or &quot;System&quot; start modes. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 TagId { get; set; }
        /// <summary>
        /// The total number of sessions on this server. <br/>
        /// This includes both connected and disconnected sessions. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 TotalSessions { get; set; }
        /// <summary>
        /// The WaitHint property specifies the estimated time required (in milliseconds) for a pending start, stop, pause, or continue operation. <br/>
        /// After the specified amount of time has elapsed, the service makes its next call to the SetServiceStatus function with either an incremented CheckPoint value or a change in Current State. <br/>
        /// If the amount of time specified by WaitHint passes, and CheckPoint has not been incremented, or the Current State has not changed, the service control manager or service control program assumes that an error has occurred. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 WaitHint { get; set; }
    }

    /// <summary>
    /// The Win32_TapeDrive class represents a tape drive on a Win32 computer. <br/>
    /// Tape drives are primarily distinguished by the fact that they can be accessed only sequentially. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {8502C4B1-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_TapeDrive
    {
        /// <summary>
        /// The availability and status of the device. <br/>
        /// For example, the Availability property indicates that the device is running and has full power (value=3), or is in a warning (4), test (5), degraded (10) or power save state (values 13-15 and 17). <br/>
        /// Regarding the power saving states, these are defined as follows: Value 13 (&quot;Power Save - Unknown&quot;) indicates that the device is known to be in a power save mode, but its exact status in this mode is unknown; 14 (&quot;Power Save - Low Power Mode&quot;) indicates that the device is in a power save state but still functioning, and may exhibit degraded performance; 15 (&quot;Power Save - Standby&quot;) describes that the device is not functioning but could be brought to full power &apos;quickly&apos;; and value 17 (&quot;Power Save - Warning&quot;) indicates that the device is in a warning state, though also in a power save mode. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 Availability { get; set; }
        /// <summary>
        /// Capabilities of the media access device. <br/>
        /// For example, the device may support &quot;Random Access&quot;, removable media and &quot;Automatic Cleaning&quot;. <br/>
        /// In this case, the values 3, 7 and 9 would be written to the array. <br/>
        /// Several of the enumerated values require some explanation: 1) Value 11, Supports Dual Sided Media, distinguishes a Device that can access both sides of dual sided Media, from a Device that reads only a single side and requires the Media to be flipped; and, 2) Value 12, Predismount Eject Not Required, indicates that Media does not have to be explicitly ejected from the Device before being accessed by a PickerElement. <br/>
        ///  <br/>
        /// arraytype: Indexed <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16[] Capabilities { get; set; }
        /// <summary>
        /// An array of free-form strings providing more detailed explanations for any of the access device features indicated in the Capabilities array. <br/>
        /// Note, each entry of this array is related to the entry in the Capabilities array that is located at the same index. <br/>
        ///  <br/>
        /// arraytype: Indexed <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String[] CapabilityDescriptions { get; set; }
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// The Compression property specifies whether hardware data compression is enabled or disabled. <br/>
        /// Values: 1 (true) or 0 (false). <br/>
        /// If true, hardware data compression is enabled. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Compression { get; set; }
        /// <summary>
        /// A free form string indicating the algorithm or tool used by the device to support compression. <br/>
        /// If it is not possible or not desired to describe the compression scheme (perhaps because it is not known), recommend using the following words: &quot;Unknown&quot; to represent that it is not known whether the device supports compression capabilities or not, &quot;Compressed&quot; to represent that the device supports compression capabilities but either its compression scheme is not known or not disclosed, and &quot;Not Compressed&quot; to represent that the devices does not support compression capabilities. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CompressionMethod { get; set; }
        /// <summary>
        /// Indicates the Win32 Configuration Manager error code. <br/>
        /// The following values may be returned: <br/>
        /// 0      This device is working properly. <br/>
        /// 1      This device is not configured correctly. <br/>
        /// 2      Windows cannot load the driver for this device. <br/>
        /// 3      The driver for this device might be corrupted, or your system may be running low on memory or other resources. <br/>
        /// 4      This device is not working properly. <br/>
        /// One of its drivers or your registry might be corrupted. <br/>
        /// 5      The driver for this device needs a resource that Windows cannot manage. <br/>
        /// 6      The boot configuration for this device conflicts with other devices. <br/>
        /// 7      Cannot filter. <br/>
        /// 8      The driver loader for the device is missing. <br/>
        /// 9      This device is not working properly because the controlling firmware is reporting the resources for the device incorrectly. <br/>
        /// 10     This device cannot start. <br/>
        /// 11     This device failed. <br/>
        /// 12     This device cannot find enough free resources that it can use. <br/>
        /// 13     Windows cannot verify this device&apos;s resources. <br/>
        /// 14     This device cannot work properly until you restart your computer. <br/>
        /// 15     This device is not working properly because there is probably a re-enumeration problem. <br/>
        /// 16     Windows cannot identify all the resources this device uses. <br/>
        /// 17     This device is asking for an unknown resource type. <br/>
        /// 18     Reinstall the drivers for this device. <br/>
        /// 19     Your registry might be corrupted. <br/>
        /// 20     Failure using the VxD loader. <br/>
        /// 21     System failure: Try changing the driver for this device. <br/>
        /// If that does not work, see your hardware documentation. <br/>
        /// Windows is removing this device. <br/>
        /// 22     This device is disabled. <br/>
        /// 23     System failure: Try changing the driver for this device. <br/>
        /// If that doesn&apos;t work, see your hardware documentation. <br/>
        /// 24     This device is not present, is not working properly, or does not have all its drivers installed. <br/>
        /// 25     Windows is still setting up this device. <br/>
        /// 26     Windows is still setting up this device. <br/>
        /// 27     This device does not have valid log configuration. <br/>
        /// 28     The drivers for this device are not installed. <br/>
        /// 29     This device is disabled because the firmware of the device did not give it the required resources. <br/>
        /// 30     This device is using an Interrupt Request (IRQ) resource that another device is using. <br/>
        /// 31     This device is not working properly because Windows cannot load the drivers required for this device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ConfigManagerErrorCode { get; set; }
        /// <summary>
        /// Indicates whether the device is using a user-defined configuration. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ConfigManagerUserConfig { get; set; }
        /// <summary>
        /// CreationClassName indicates the name of the class or the subclass used in the creation of an instance. <br/>
        /// When used with the other key properties of this class, this property allows all instances of this class and its subclasses to be uniquely identified. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CreationClassName { get; set; }
        /// <summary>
        /// Default block size, in bytes, for this device. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: bytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 DefaultBlockSize { get; set; }
        /// <summary>
        /// The Description property provides a textual description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The DeviceID property contains a string uniquely identifying the tape drive with other devices on the system. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: DeviceId <br/>
        ///  <br/>
        /// </summary>
        public String DeviceID { get; set; }
        /// <summary>
        /// The ECC property specifies whether the device supports hardware error correction. <br/>
        /// Values: 1 (true) or 0 (false). <br/>
        /// If true, hardware error correction is supported. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ECC { get; set; }
        /// <summary>
        /// EOTWarningZoneSize indicates the size, in bytes, of the area designated as &apos;end of tape&apos;. <br/>
        /// Access in this area generates an &apos;end of tape&apos; warning. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// units: bytes <br/>
        ///  <br/>
        /// </summary>
        public UInt32 EOTWarningZoneSize { get; set; }
        /// <summary>
        /// ErrorCleared is a boolean property indicating that the error reported in LastErrorCode property is now cleared. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ErrorCleared { get; set; }
        /// <summary>
        /// ErrorDescription is a free-form string supplying more information about the error recorded in LastErrorCode property, and information on any corrective actions that may be taken. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ErrorDescription { get; set; }
        /// <summary>
        /// ErrorMethodology is a free-form string describing the type(s) of error detection and correction supported by this device. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ErrorMethodology { get; set; }
        /// <summary>
        /// The FeaturesHigh property specifies the high-order 32 bits of the device features flag. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 FeaturesHigh { get; set; }
        /// <summary>
        /// The FeaturesLow property specifies the low-order 32 bits of the device features flag. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 FeaturesLow { get; set; }
        /// <summary>
        /// The Id property indicates the manufacturer&apos;s identifying name of the Win32 CD ROM drive. <br/>
        /// Example: PLEXTOR CD-ROM PX-12CS 1.01 <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Id { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// LastErrorCode captures the last error code reported by the logical device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 LastErrorCode { get; set; }
        /// <summary>
        /// The Manufacturer property indicates the manufacturer of the Win32 CD-ROM drive. <br/>
        /// Example: PLEXTOR <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Manufacturer { get; set; }
        /// <summary>
        /// Maximum block size, in bytes, for media accessed by this device. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: bytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 MaxBlockSize { get; set; }
        /// <summary>
        /// Maximum size, in Kbytes, of media supported by this device. <br/>
        /// KBytes is interpreted as the number of bytes multiplied by 1000 (NOT the number of bytes multiplied by 1024). <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: kilobytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 MaxMediaSize { get; set; }
        /// <summary>
        /// The MaxPartitionCount property indicates the maximum part count for the tape drive. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 MaxPartitionCount { get; set; }
        /// <summary>
        /// The MediaType property specifies the media type used by (or accessed by) this device. <br/>
        /// In this case, it is set to &quot;Tape Drive&quot;. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String MediaType { get; set; }
        /// <summary>
        /// Minimum block size, in bytes, for media accessed by this device. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: bytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 MinBlockSize { get; set; }
        /// <summary>
        /// The Name property defines the label by which the object is known. <br/>
        /// When subclassed, the Name property can be overridden to be a Key property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// Boolean indicating that the media access device needs cleaning. <br/>
        /// Whether manual or automatic cleaning is possible is indicated in the Capabilities array property. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean NeedsCleaning { get; set; }
        /// <summary>
        /// When the media access device supports multiple individual media, this property defines the maximum number which can be supported or inserted. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 NumberOfMediaSupported { get; set; }
        /// <summary>
        /// Padding indicates the number of bytes inserted between blocks on a tape Media. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// units: bytes <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Padding { get; set; }
        /// <summary>
        /// Indicates the Win32 Plug and Play device ID of the logical device. <br/>
        /// Example: *PNP030b <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String PNPDeviceID { get; set; }
        /// <summary>
        /// Indicates the specific power-related capabilities of the logical device. <br/>
        /// The array values, 0=&quot;Unknown&quot;, 1=&quot;Not Supported&quot; and 2=&quot;Disabled&quot; are self-explanatory. <br/>
        /// The value, 3=&quot;Enabled&quot; indicates that the power management features are currently enabled but the exact feature set is unknown or the information is unavailable. <br/>
        /// &quot;Power Saving Modes Entered Automatically&quot; (4) describes that a device can change its power state based on usage or other criteria. <br/>
        /// &quot;Power State Settable&quot; (5) indicates that the SetPowerState method is supported. <br/>
        /// &quot;Power Cycling Supported&quot; (6) indicates that the SetPowerState method can be invoked with the PowerState input variable set to 5 (&quot;Power Cycle&quot;). <br/>
        /// &quot;Timed Power On Supported&quot; (7) indicates that the SetPowerState method can be invoked with the PowerState input variable set to 5 (&quot;Power Cycle&quot;) and the Time parameter set to a specific date and time, or interval, for power-on. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16[] PowerManagementCapabilities { get; set; }
        /// <summary>
        /// Boolean indicating that the Device can be power managed - ie, put into a power save state. <br/>
        /// This boolean does not indicate that power management features are currently enabled, or if enabled, what features are supported. <br/>
        /// Refer to the PowerManagementCapabilities array for this information. <br/>
        /// If this boolean is false, the integer value 1, for the string, &quot;Not Supported&quot;, should be the only entry in the PowerManagementCapabilities array. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean PowerManagementSupported { get; set; }
        /// <summary>
        /// The ReportSetMarks property specifies whether setmark reporting is enabled. <br/>
        /// Setmark reporting makes use of a specialized recorded element that does not contain user data. <br/>
        /// This recorded element is used to provide a segmentation scheme. <br/>
        /// This segmentation scheme is hierarchically superior to filemarks. <br/>
        /// Setmarks provide faster positioning on high-capacity tapes. <br/>
        /// Values: 1 (true) or 0 (false). <br/>
        /// If true, setmark reporting is enabled. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ReportSetMarks { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// StatusInfo is a string indicating whether the logical device is in an enabled (value = 3), disabled (value = 4) or some other (1) or unknown (2) state. <br/>
        /// If this property does not apply to the logical device, the value, 5 (&quot;Not Applicable&quot;), should be used. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 StatusInfo { get; set; }
        /// <summary>
        /// The scoping System&apos;s CreationClassName. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.CreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String SystemCreationClassName { get; set; }
        /// <summary>
        /// The scoping System&apos;s Name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.Name <br/>
        ///  <br/>
        /// </summary>
        public String SystemName { get; set; }
    }

    /// <summary>
    /// The Win32_TemperatureProbe class represents the properties of a temperature sensor (electronic thermometer). <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {464FFABB-946F-11d2-AAE2-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_TemperatureProbe
    {
        /// <summary>
        /// Indicates the accuracy of the sensor for the measured property. <br/>
        /// Its value is recorded as plus/minus hundredths of a percent. <br/>
        /// Accuracy, along with resolution and tolerance, is used to calculate the actual value of the measured physical property. <br/>
        /// Accuracy may vary depending on whether the device is linear over its dynamic range. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: hundredths of percent <br/>
        ///  <br/>
        /// </summary>
        public int Accuracy { get; set; }
        /// <summary>
        /// The availability and status of the device. <br/>
        /// For example, the Availability property indicates that the device is running and has full power (value=3), or is in a warning (4), test (5), degraded (10) or power save state (values 13-15 and 17). <br/>
        /// Regarding the power saving states, these are defined as follows: Value 13 (&quot;Power Save - Unknown&quot;) indicates that the device is known to be in a power save mode, but its exact status in this mode is unknown; 14 (&quot;Power Save - Low Power Mode&quot;) indicates that the device is in a power save state but still functioning, and may exhibit degraded performance; 15 (&quot;Power Save - Standby&quot;) describes that the device is not functioning but could be brought to full power &apos;quickly&apos;; and value 17 (&quot;Power Save - Warning&quot;) indicates that the device is in a warning state, though also in a power save mode. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 Availability { get; set; }
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// Indicates the Win32 Configuration Manager error code. <br/>
        /// The following values may be returned: <br/>
        /// 0      This device is working properly. <br/>
        /// 1      This device is not configured correctly. <br/>
        /// 2      Windows cannot load the driver for this device. <br/>
        /// 3      The driver for this device might be corrupted, or your system may be running low on memory or other resources. <br/>
        /// 4      This device is not working properly. <br/>
        /// One of its drivers or your registry might be corrupted. <br/>
        /// 5      The driver for this device needs a resource that Windows cannot manage. <br/>
        /// 6      The boot configuration for this device conflicts with other devices. <br/>
        /// 7      Cannot filter. <br/>
        /// 8      The driver loader for the device is missing. <br/>
        /// 9      This device is not working properly because the controlling firmware is reporting the resources for the device incorrectly. <br/>
        /// 10     This device cannot start. <br/>
        /// 11     This device failed. <br/>
        /// 12     This device cannot find enough free resources that it can use. <br/>
        /// 13     Windows cannot verify this device&apos;s resources. <br/>
        /// 14     This device cannot work properly until you restart your computer. <br/>
        /// 15     This device is not working properly because there is probably a re-enumeration problem. <br/>
        /// 16     Windows cannot identify all the resources this device uses. <br/>
        /// 17     This device is asking for an unknown resource type. <br/>
        /// 18     Reinstall the drivers for this device. <br/>
        /// 19     Your registry might be corrupted. <br/>
        /// 20     Failure using the VxD loader. <br/>
        /// 21     System failure: Try changing the driver for this device. <br/>
        /// If that does not work, see your hardware documentation. <br/>
        /// Windows is removing this device. <br/>
        /// 22     This device is disabled. <br/>
        /// 23     System failure: Try changing the driver for this device. <br/>
        /// If that doesn&apos;t work, see your hardware documentation. <br/>
        /// 24     This device is not present, is not working properly, or does not have all its drivers installed. <br/>
        /// 25     Windows is still setting up this device. <br/>
        /// 26     Windows is still setting up this device. <br/>
        /// 27     This device does not have valid log configuration. <br/>
        /// 28     The drivers for this device are not installed. <br/>
        /// 29     This device is disabled because the firmware of the device did not give it the required resources. <br/>
        /// 30     This device is using an Interrupt Request (IRQ) resource that another device is using. <br/>
        /// 31     This device is not working properly because Windows cannot load the drivers required for this device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ConfigManagerErrorCode { get; set; }
        /// <summary>
        /// Indicates whether the device is using a user-defined configuration. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ConfigManagerUserConfig { get; set; }
        /// <summary>
        /// CreationClassName indicates the name of the class or the subclass used in the creation of an instance. <br/>
        /// When used with the other key properties of this class, this property allows all instances of this class and its subclasses to be uniquely identified. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CreationClassName { get; set; }
        /// <summary>
        /// The current value indicated by the sensor. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int CurrentReading { get; set; }
        /// <summary>
        /// The Description property provides a textual description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The DeviceID property contains a string identifying the temperature probe. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: DeviceId <br/>
        ///  <br/>
        /// </summary>
        public String DeviceID { get; set; }
        /// <summary>
        /// ErrorCleared is a boolean property indicating that the error reported in LastErrorCode property is now cleared. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ErrorCleared { get; set; }
        /// <summary>
        /// ErrorDescription is a free-form string supplying more information about the error recorded in LastErrorCode property, and information on any corrective actions that may be taken. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ErrorDescription { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// Indicates that the sensor is linear over its dynamic range. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean IsLinear { get; set; }
        /// <summary>
        /// LastErrorCode captures the last error code reported by the logical device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 LastErrorCode { get; set; }
        /// <summary>
        /// The Sensor&apos;s threshold values specify the ranges (min and max values) for determining whether the Sensor is operating under Normal, NonCritical, Critical or Fatal conditions. <br/>
        /// If the CurrentReading is between LowerThresholdCritical and LowerThresholdFatal, then the CurrentState is Critical. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int LowerThresholdCritical { get; set; }
        /// <summary>
        /// The sensor&apos;s threshold values specify the ranges (min and max values) for determining whether the Sensor is operating under Normal, NonCritical, Critical or Fatal conditions. <br/>
        /// If the CurrentReading is below LowerThresholdFatal, then the CurrentState is Fatal. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int LowerThresholdFatal { get; set; }
        /// <summary>
        /// The sensor&apos;s threshold values specify the ranges (min and max values) for determining whether the Sensor is operating under Normal, NonCritical, Critical or Fatal conditions. <br/>
        /// If CurrentReading is between LowerThresholdNonCritical and UpperThresholdNonCritical, then the Sensor is reporting a normal value. <br/>
        /// If CurrentReading is between LowerThresholdNonCritical and LowerThresholdCritical, then the CurrentState is NonCritical. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int LowerThresholdNonCritical { get; set; }
        /// <summary>
        /// MaxReadable indicates the largest value of the measured property that can be read by the numeric sensor. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int MaxReadable { get; set; }
        /// <summary>
        /// MinReadable indicates the smallest value of the measured property that can be read by the numeric sensor. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int MinReadable { get; set; }
        /// <summary>
        /// The Name property defines the label by which the object is known. <br/>
        /// When subclassed, the Name property can be overridden to be a Key property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// NominalReading indicates the &apos;normal&apos; or expected value for the numeric sensor. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int NominalReading { get; set; }
        /// <summary>
        /// NormalMax provides guidance for the user as to the normal maximum range for the numeric sensor. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int NormalMax { get; set; }
        /// <summary>
        /// NormalMin provides guidance for the user as to the normal minimum range for the numeric sensor. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int NormalMin { get; set; }
        /// <summary>
        /// Indicates the Win32 Plug and Play device ID of the logical device. <br/>
        /// Example: *PNP030b <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String PNPDeviceID { get; set; }
        /// <summary>
        /// Indicates the specific power-related capabilities of the logical device. <br/>
        /// The array values, 0=&quot;Unknown&quot;, 1=&quot;Not Supported&quot; and 2=&quot;Disabled&quot; are self-explanatory. <br/>
        /// The value, 3=&quot;Enabled&quot; indicates that the power management features are currently enabled but the exact feature set is unknown or the information is unavailable. <br/>
        /// &quot;Power Saving Modes Entered Automatically&quot; (4) describes that a device can change its power state based on usage or other criteria. <br/>
        /// &quot;Power State Settable&quot; (5) indicates that the SetPowerState method is supported. <br/>
        /// &quot;Power Cycling Supported&quot; (6) indicates that the SetPowerState method can be invoked with the PowerState input variable set to 5 (&quot;Power Cycle&quot;). <br/>
        /// &quot;Timed Power On Supported&quot; (7) indicates that the SetPowerState method can be invoked with the PowerState input variable set to 5 (&quot;Power Cycle&quot;) and the Time parameter set to a specific date and time, or interval, for power-on. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16[] PowerManagementCapabilities { get; set; }
        /// <summary>
        /// Boolean indicating that the Device can be power managed - ie, put into a power save state. <br/>
        /// This boolean does not indicate that power management features are currently enabled, or if enabled, what features are supported. <br/>
        /// Refer to the PowerManagementCapabilities array for this information. <br/>
        /// If this boolean is false, the integer value 1, for the string, &quot;Not Supported&quot;, should be the only entry in the PowerManagementCapabilities array. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean PowerManagementSupported { get; set; }
        /// <summary>
        /// Resolution indicates the ability of the sensor to resolve differences in the measured property. <br/>
        /// This value may vary depending on whether the device is linear over its dynamic range. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// units: hundredths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Resolution { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// StatusInfo is a string indicating whether the logical device is in an enabled (value = 3), disabled (value = 4) or some other (1) or unknown (2) state. <br/>
        /// If this property does not apply to the logical device, the value, 5 (&quot;Not Applicable&quot;), should be used. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 StatusInfo { get; set; }
        /// <summary>
        /// The scoping System&apos;s CreationClassName. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.CreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String SystemCreationClassName { get; set; }
        /// <summary>
        /// The scoping System&apos;s Name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.Name <br/>
        ///  <br/>
        /// </summary>
        public String SystemName { get; set; }
        /// <summary>
        /// Indicates the tolerance of the sensor for the measured property. <br/>
        /// Tolerance, along with resolution and accuracy, is used to calculate the actual value of the measured physical property. <br/>
        /// Tolerance may vary depending on whether the device is linear over its dynamic range. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int Tolerance { get; set; }
        /// <summary>
        /// The sensor&apos;s threshold values specify the ranges (min and max values) for determining whether the Sensor is operating under Normal, NonCritical, Critical or Fatal conditions. <br/>
        /// If the CurrentReading is between UpperThresholdCritical and UpperThresholdFatal, then the CurrentState is Critical. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int UpperThresholdCritical { get; set; }
        /// <summary>
        /// The sensor&apos;s threshold values specify the ranges (min and max values) for determining whether the Sensor is operating under Normal, NonCritical, Critical or Fatal conditions. <br/>
        /// If the CurrentReading is above UpperThresholdFatal, then the CurrentState is Fatal. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int UpperThresholdFatal { get; set; }
        /// <summary>
        /// The sensor&apos;s threshold values specify the ranges (min and max values) for determining whether the Sensor is operating under Normal, NonCritical, Critical or Fatal conditions. <br/>
        /// If the CurrentReading is between LowerThresholdNonCritical and UpperThresholdNonCritical, then the Sensor is reporting a normal value. <br/>
        /// If the CurrentReading is between UpperThresholdNonCritical and UpperThresholdCritical, then the CurrentState is NonCritical. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: tenths of degrees centigrade <br/>
        ///  <br/>
        /// </summary>
        public int UpperThresholdNonCritical { get; set; }
    }

    /// <summary>
    /// The Win32_Thread class represents a thread of execution.While a process must have one thread of execution, the process can create other threads to execute tasks in parallel. <br/>
    /// Threads share the process environment, thus multiple threads under the same process use less memory than the same number of processes. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {8502C4DD-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_Thread
    {
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// CreationClassName indicates the name of the class or the subclass used in the creation of an instance. <br/>
        /// When used with the other key properties of this class, this property allow all instances of this class and its subclasses to be uniquely identified. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CreationClassName { get; set; }
        /// <summary>
        /// The scoping computer system&apos;s creation class name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_Process.CSCreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String CSCreationClassName { get; set; }
        /// <summary>
        /// The scoping computer system&apos;s name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_Process.CSName <br/>
        ///  <br/>
        /// </summary>
        public String CSName { get; set; }
        /// <summary>
        /// The Description property provides a textual description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The ElapsedTime property indicates the total execution time given to this thread since its creation. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: milliseconds <br/>
        ///  <br/>
        /// </summary>
        public UInt64 ElapsedTime { get; set; }
        /// <summary>
        /// Indicates the current operating condition of the thread. <br/>
        /// Values include ready (2), running (3), and blocked (4), among others. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 ExecutionState { get; set; }
        /// <summary>
        /// The Handle property represents a handle to a thread. <br/>
        /// The handle has full access rights by default. <br/>
        /// With the correct security access, the handle can be used in any function that accepts a thread handle. <br/>
        /// Depending on the inheritance flag specified when it is created, this handle can be inherited by child processes. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: Handle <br/>
        ///  <br/>
        /// </summary>
        public String Handle { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// The KernelModeTime property indicates the raw counter data from the performance counter type <br/>
        /// PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE | PERF_TIMER_100NS | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT <br/>
        /// The counter data is in 100 nanosecond units. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// override: KernelModeTime <br/>
        ///  <br/>
        /// units: 100 nanoseconds <br/>
        ///  <br/>
        /// </summary>
        public UInt64 KernelModeTime { get; set; }
        /// <summary>
        /// The Name property defines the label by which the object is known. <br/>
        /// When subclassed, the Name property can be overridden to be a Key property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The scoping operating system&apos;s creation class name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_Process.OSCreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String OSCreationClassName { get; set; }
        /// <summary>
        /// The scoping operating system&apos;s name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_Process.OSName <br/>
        ///  <br/>
        /// </summary>
        public String OSName { get; set; }
        /// <summary>
        /// The Priority property indicates the dynamic priority of the thread. <br/>
        /// Each thread has a dynamic priority that the scheduler uses to determine which thread to execute. <br/>
        /// Initially, a thread&apos;s dynamic priority is the same as its base priority. <br/>
        /// The system can raise and lower the dynamic priority, to ensure that it is responsive (guaranteeing that no threads are starved for processor time). <br/>
        /// The system does not boost the priority of threads with a base priority level between 16 and 31. <br/>
        /// Only threads with a base priority between 0 and 15 receive dynamic priority boosts. <br/>
        /// Higher numbers indicate higher priorities. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// override: Priority <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Priority { get; set; }
        /// <summary>
        /// The PriorityBase property indicates the current base priority of a thread. <br/>
        /// The operating system may raise the thread&apos;s dynamic priority above the base priority if the thread is handling user input, or lower it toward the base priority if the thread becomes compute-bound. <br/>
        /// The PriorityBase propertycan have a value between 0 and 31 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 PriorityBase { get; set; }
        /// <summary>
        /// The scoping process&apos; CreationClassName. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_Process.CreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String ProcessCreationClassName { get; set; }
        /// <summary>
        /// The ProcessHandle property indicates the process that created the thread. <br/>
        /// The contents of this property can be used by Win32 API elements. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: ProcessHandle <br/>
        ///  <br/>
        /// propagated: CIM_Process.Handle <br/>
        ///  <br/>
        /// </summary>
        public String ProcessHandle { get; set; }
        /// <summary>
        /// The StartAddress property indicates the starting address of the thread. <br/>
        /// Because any application with appropriate access to the thread can change the thread&apos;s context, this value may only be an approximation of the thread&apos;s starting address. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 StartAddress { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// The ThreadState property indicates the current execution state for the thread. <br/>
        /// A thread can have one of eight values: Initialized (recognized by the microkernel), Ready (prepared to run on next available processor), Running (executing), Standby (about to run, only one thread may be in this state at a time), Terminated (finished executing), Waiting (not ready for the processor, when ready, it will be rescheduled), Transition (thread is waiting for resources other than the processor), and Unknown (the thread state is unknown). <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ThreadState { get; set; }
        /// <summary>
        /// The ThreadWaitReason property indicates why the thread is waiting. <br/>
        /// The value is only valid if the ThreadState member is set to Waiting. <br/>
        /// Values of 0 or 7 denote that the thread is waiting for the Executive, 1 or 8 for a Free Page, 2 or 9 for a Page In, 3 or 10 for a Pool Allocation, 4 or 11 for an Execution Delay, 5 or 12 for a Suspended condition, 6 or 13 for a User Request, 14 for an Event Pair High, 15 for an Event Pair Low, 16 for an Local Procedure Call (LPC) Receive, 17 for an LPC Reply, 18 for Virtual Memory, 19 for a Page Out. <br/>
        /// 20 and higher are not assigned. <br/>
        /// Event Pairs allow communication with protected subsystems (see Context Switches). <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ThreadWaitReason { get; set; }
        /// <summary>
        /// The UserModeTime property indicates the raw counter data from the performance counter type <br/>
        /// PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE | PERF_TIMER_100NS | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT <br/>
        /// The counter data is in 100 nanosecond units. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// override: UserModeTime <br/>
        ///  <br/>
        /// units: 100 nanoseconds <br/>
        ///  <br/>
        /// </summary>
        public UInt64 UserModeTime { get; set; }
    }

    /// <summary>
    /// The Win32_TCPIPPrinterPort class represents a TCP//IP service access point. <br/>
    /// For example a TCP/IP printer port. <br/>
    /// Note:  The SE_LOAD_DRIVER_PRIVILEGE privilege is required on this class. <br/>
    ///  <br/>
    /// createby: PutInstance <br/>
    ///  <br/>
    /// deleteby: DeleteInstance <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {553644e9-f998-48c3-b037-26e5909f4333} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_TCPIPPrinterPort
    {
        /// <summary>
        /// The ByteCount property, when true, causes the computer to count the number of bytes in a document before sending them to the printer and the printer to report back the number of bytes actually read. <br/>
        /// This is used for diagnostics when one discovers that bytes are missing from the print output. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ByteCount { get; set; }
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// CreationClassName indicates the name of the class or the subclass used in the creation of an instance. <br/>
        /// When used with the other key properties of this class, this property allows all instances of this class and its subclasses to be uniquely identified. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CreationClassName { get; set; }
        /// <summary>
        /// The Description property provides a textual description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The HostAddress property indicates the address of device or print server <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String HostAddress { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// The Name property uniquely identifies the service access point and provides an indication of the functionality that is managed. <br/>
        /// This functionality is described in more detail in the object&apos;s Description property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The PortNumber property indicates the number of the TCP port used by the port monitor to communitcate with the device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 PortNumber { get; set; }
        /// <summary>
        /// The Protocol property has two values: &apos;Raw&apos; indicates printing directly to a device and &apos;Lpr&apos; indicates printing to device or print server; LPR is a legacy protocol, which will eventually be replaced by RAW. <br/>
        /// Some printers support only LPR. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Protocol { get; set; }
        /// <summary>
        /// The Queue property is used with the LPR protocol to indicate the name of the print queue on the server. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Queue { get; set; }
        /// <summary>
        /// The SNMPCommunity property contains a security level value for the device. <br/>
        /// For example &apos;public&apos;. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SNMPCommunity { get; set; }
        /// <summary>
        /// The property SNMPDevIndex indicates the SNMP index number of this device for the SNMP agent. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 SNMPDevIndex { get; set; }
        /// <summary>
        /// The SNMPEnabled property, when true, indicates that this printer supports RFC1759 (Simple Network Management Protocol) and can provide rich status information from the device. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean SNMPEnabled { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// The scoping system&apos;s creation class name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.CreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String SystemCreationClassName { get; set; }
        /// <summary>
        /// The scoping system&apos;s name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.Name <br/>
        ///  <br/>
        /// </summary>
        public String SystemName { get; set; }
        /// <summary>
        /// The Type property indicates the type of SAP such as &apos;attached&apos; or &apos;Redirected&apos;. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// schema: Win32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Type { get; set; }
    }

    /// <summary>
    /// The Win32_TimeZone class represents the time zone information for a Win32 system. <br/>
    /// This includes changes needed for the transition to and from daylight savings time. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {8502C4EC-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_TimeZone
    {
        /// <summary>
        /// The Bias property specifies the current bias for local time translation. <br/>
        /// The bias is the difference between Coordinated Universal Time (UTC) and local time. <br/>
        /// All translations between UTC and local time are based on the following formula: UTC = local time + bias. <br/>
        /// This member is required. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: minutes <br/>
        ///  <br/>
        /// </summary>
        public int Bias { get; set; }
        /// <summary>
        /// A short textual description (one-line string) of the CIM_Setting object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// The DaylightBias property specifies a bias value to be used during local time translations that occur during daylight time. <br/>
        /// This member is ignored if a value for the DaylightDay member is not supplied. <br/>
        /// The value of this member is added to the Bias member to form the bias used during daylight time. <br/>
        /// In most time zones, the value of this member is -60. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// units: minutes <br/>
        ///  <br/>
        /// </summary>
        public int DaylightBias { get; set; }
        /// <summary>
        /// The DaylightDay property specifies the DaylightDayOfWeek ofthe DaylightMonth when the transition from standard time to daylight savingstime occurs on this operating system. <br/>
        /// Example: 15 <br/>
        /// If  the transition day DaylightDayOfWeek occurs on a Sunday, then the value 1 denotes the first Sunday of the DaylightMonth, 2 denotesthe second Sunday, and so forth, and 5 denotes the last Sunday of theDaylightMonth. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 DaylightDay { get; set; }
        /// <summary>
        /// The DaylightDayOfWeek property specifies the day of the week when the transition from standard time to daylight savings time occurs on this operating system. <br/>
        /// Example: 1 <br/>
        ///  <br/>
        /// cimtype: uint8 <br/>
        ///  <br/>
        /// </summary>
        public byte DaylightDayOfWeek { get; set; }
        /// <summary>
        /// The DaylightHour property specifies the hour of the day when the transition from standard time to daylight savings time occurs on this operating system. <br/>
        /// Example: 2 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 DaylightHour { get; set; }
        /// <summary>
        /// The DaylightMillisecond property specifies the millisecond of the DaylightSecond when the transition from standard time to daylight savings time occurs on this operating system. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 DaylightMillisecond { get; set; }
        /// <summary>
        /// The DaylightMinute property specifies the minute of the DaylightHour when the transition from standard time to daylight savings time occurs on this operating system. <br/>
        /// Example: 59 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 DaylightMinute { get; set; }
        /// <summary>
        /// The DaylightMonth property specifies the month when the transition from standard time to daylight savings time occurs on this operating system. <br/>
        /// Example: 1 = January <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 DaylightMonth { get; set; }
        /// <summary>
        /// The DaylightName property indicates the name of the time zone being represented when daylight savings time is in effect. <br/>
        /// Example: EDT = Eastern Daylight Time. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String DaylightName { get; set; }
        /// <summary>
        /// The DaylightSecond property specifies the second of of the DaylightMinute when the transition from standard time to daylight savings time occurs on this operating system. <br/>
        /// Example: 59 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 DaylightSecond { get; set; }
        /// <summary>
        /// The DaylightYear property indicates the year when daylight saving time is in effect. <br/>
        /// This member is not required. <br/>
        /// Example: 1997 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 DaylightYear { get; set; }
        /// <summary>
        /// A textual description of the CIM_Setting object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The identifier by which the CIM_Setting object is known. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SettingID { get; set; }
        /// <summary>
        /// The StandardBias property specifies a bias value to be used when daylight savings time is not in effect. <br/>
        /// This member is ignored if a value for the StandardDay member is not supplied. <br/>
        /// The value of this member is added to the Bias member to form the bias during standard time. <br/>
        /// Example: 0 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// units: minutes <br/>
        ///  <br/>
        /// </summary>
        public UInt32 StandardBias { get; set; }
        /// <summary>
        /// The StandardDay property specifies the StandardDayOfWeekof the StandardMonth when the transition from daylight saving time to standardtime occurs on this operating system. <br/>
        /// Example: 31 <br/>
        /// If  the transition day StandardDayOfWeek  occurs on a Sunday, then thevalue 1 denotes the first Sunday of the StandardMonth, 2 denotes the secondSunday, and so forth, and 5 denotes the last Sunday of the StandardMonth. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 StandardDay { get; set; }
        /// <summary>
        /// The StandardDayOfWeek property specifies the day of the week when the transition from daylight savings time to standard time occurs on this operating system. <br/>
        /// Example: 1 <br/>
        ///  <br/>
        /// cimtype: uint8 <br/>
        ///  <br/>
        /// </summary>
        public byte StandardDayOfWeek { get; set; }
        /// <summary>
        /// The StandardHour property specifies the hour of the day when the transition from daylight savings time to standard time occurs on this operating system. <br/>
        /// Example: 11 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 StandardHour { get; set; }
        /// <summary>
        /// The StandardMillisecond property specifies the millisecond of the StandardSecond when the transition from daylight savings time to standard time occurs on this operating system. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 StandardMillisecond { get; set; }
        /// <summary>
        /// The StandardMinute property specifies the minute of the StandardDay when the transition from daylight savings time to standard time occurs on this operating system. <br/>
        /// Example: 59 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 StandardMinute { get; set; }
        /// <summary>
        /// The StandardMonth property specifies the month when the transition from daylight savings time to standard time occurs on this operating system. <br/>
        /// Example: 12 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 StandardMonth { get; set; }
        /// <summary>
        /// The StandardName property indicates the name of the time zone being represented when standard time is in effect. <br/>
        /// Example: EST = Eastern Standard Time. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String StandardName { get; set; }
        /// <summary>
        /// The StandardSecond property specifies the second of the StandardMinute when the transition from daylight savings time to standard time occurs on this operating system. <br/>
        /// Example: 59 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 StandardSecond { get; set; }
        /// <summary>
        /// The StandardYear property indicates the year when standard time is in effect. <br/>
        /// This member is not required. <br/>
        /// Example: 1997 <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 StandardYear { get; set; }
    }

    /// <summary>
    /// Specifies a trustee. <br/>
    /// Either a name or a SID (byte array) can be used <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// uuid: {8502C589-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_Trustee
    {
        /// <summary>
        /// The domain portion of the account <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Domain { get; set; }
        /// <summary>
        /// The name portion of the account <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The SID of the trustee <br/>
        ///  <br/>
        /// cimtype: uint8 <br/>
        ///  <br/>
        /// </summary>
        public byte[] SID { get; set; }
        /// <summary>
        /// The length of the SID in BYTES <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 SidLength { get; set; }
        /// <summary>
        /// The SID of the trustee in string format (e.g., S-1-1-0) <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String SIDString { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 TIME_CREATED { get; set; }
    }

    /// <summary>
    /// The RegisterTypeLibraries action registers type libraries with the system. <br/>
    /// The action works on each file referenced which is triggered to be installed. <br/>
    ///  <br/>
    /// provider: MSIProv <br/>
    ///  <br/>
    /// uuid: {5D06847A-DB34-11d2-85FC-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_TypeLibraryAction
    {
        /// <summary>
        /// The ActionID property is a unique identifier assigned to a particular  action for a software element. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ActionID { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// The cost associated with the registration of the type library in bytes. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Cost { get; set; }
        /// <summary>
        /// A description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The Direction property indicates whether a particular   CIM_Action object is part of a sequence of actions to transition the   current software element to its next state, such as &quot;Install&quot; or to  remove the current software element, such as &quot;Uninstall&quot;. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 Direction { get; set; }
        /// <summary>
        /// The language of the type library. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 Language { get; set; }
        /// <summary>
        /// The GUID that identifies the library. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String LibID { get; set; }
        /// <summary>
        /// Name is used to identify this software element <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.Name <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The SoftwareElementID is an identifier for this software element. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementID <br/>
        ///  <br/>
        /// </summary>
        public String SoftwareElementID { get; set; }
        /// <summary>
        /// The SoftwareElementState indicates the state of a software element <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementState <br/>
        ///  <br/>
        /// </summary>
        public UInt16 SoftwareElementState { get; set; }
        /// <summary>
        /// The TargetOperatingSystem indicates the target operating system of the owning software element. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.TargetOperatingSystem <br/>
        ///  <br/>
        /// </summary>
        public UInt16 TargetOperatingSystem { get; set; }
        /// <summary>
        /// Version should be in the form &lt;major&gt;.&lt;minor&gt;.&lt;revision&gt; or &lt;major&gt;.&lt;minor&gt;&lt;letter&gt;&lt;revision&gt;. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.Version <br/>
        ///  <br/>
        /// </summary>
        public String Version { get; set; }
    }

    /// <summary>
    /// The Win32_TokenPrivileges abstract class contains information about a set of privileges for an access token. <br/>
    /// Each process or thread in the job object has an access token specifying what resources and actions are available to it. <br/>
    /// For more information, see the Access Tokens topic in the Platform SDK Access Control documentation. <br/>
    ///  <br/>
    /// uuid: {3559D159-47E8-4458-9B7E-5FD16D260B8D} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_TokenPrivileges
    {
        /// <summary>
        /// Specifies the number of entries in the Privileges array. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 PrivilegeCount { get; set; }
        /// <summary>
        /// Specifies an array of LUIDs and attributes. <br/>
        ///  <br/>
        /// cimtype: object:Win32_LUIDandAttributes <br/>
        ///  <br/>
        /// </summary>
        public Object[] Privileges { get; set; }
    }

    /// <summary>
    /// The Win32_TokenGroups abstract class contains information about the group account security identifiers (SIDs) associated with an access token. <br/>
    /// For more information about token groups and the TOKEN_GROUPS structure, see the Access Tokens topic in the Platform SDK Access Control documentation. <br/>
    ///  <br/>
    /// uuid: {6CDD7B40-369D-4725-AB7F-EFE53EE2C455} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_TokenGroups
    {
        /// <summary>
        /// Specifies the number of groups in the access token. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 GroupCount { get; set; }
        /// <summary>
        /// Specifies an array of SIDs and attributes. <br/>
        ///  <br/>
        /// cimtype: object:Win32_SIDandAttributes <br/>
        ///  <br/>
        /// </summary>
        public Object[] Groups { get; set; }
    }
}
