// <auto-generated />

using System;

namespace CIMV2
{
    /// <summary>
    /// The Win32_HeatPipe class represents the properties of a heat pipe cooling device. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {464FFAB7-946F-11d2-AAE2-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_HeatPipe
    {
        /// <summary>
        /// ActiveCooling is a boolean indicating that the cooling device provides active (as opposed to passive) cooling. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ActiveCooling { get; set; }
        /// <summary>
        /// The availability and status of the device. <br/>
        /// For example, the Availability property indicates that the device is running and has full power (value=3), or is in a warning (4), test (5), degraded (10) or power save state (values 13-15 and 17). <br/>
        /// Regarding the power saving states, these are defined as follows: Value 13 (&quot;Power Save - Unknown&quot;) indicates that the device is known to be in a power save mode, but its exact status in this mode is unknown; 14 (&quot;Power Save - Low Power Mode&quot;) indicates that the device is in a power save state but still functioning, and may exhibit degraded performance; 15 (&quot;Power Save - Standby&quot;) describes that the device is not functioning but could be brought to full power &apos;quickly&apos;; and value 17 (&quot;Power Save - Warning&quot;) indicates that the device is in a warning state, though also in a power save mode. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 Availability { get; set; }
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// Indicates the Win32 Configuration Manager error code. <br/>
        /// The following values may be returned: <br/>
        /// 0      This device is working properly. <br/>
        /// 1      This device is not configured correctly. <br/>
        /// 2      Windows cannot load the driver for this device. <br/>
        /// 3      The driver for this device might be corrupted, or your system may be running low on memory or other resources. <br/>
        /// 4      This device is not working properly. <br/>
        /// One of its drivers or your registry might be corrupted. <br/>
        /// 5      The driver for this device needs a resource that Windows cannot manage. <br/>
        /// 6      The boot configuration for this device conflicts with other devices. <br/>
        /// 7      Cannot filter. <br/>
        /// 8      The driver loader for the device is missing. <br/>
        /// 9      This device is not working properly because the controlling firmware is reporting the resources for the device incorrectly. <br/>
        /// 10     This device cannot start. <br/>
        /// 11     This device failed. <br/>
        /// 12     This device cannot find enough free resources that it can use. <br/>
        /// 13     Windows cannot verify this device&apos;s resources. <br/>
        /// 14     This device cannot work properly until you restart your computer. <br/>
        /// 15     This device is not working properly because there is probably a re-enumeration problem. <br/>
        /// 16     Windows cannot identify all the resources this device uses. <br/>
        /// 17     This device is asking for an unknown resource type. <br/>
        /// 18     Reinstall the drivers for this device. <br/>
        /// 19     Your registry might be corrupted. <br/>
        /// 20     Failure using the VxD loader. <br/>
        /// 21     System failure: Try changing the driver for this device. <br/>
        /// If that does not work, see your hardware documentation. <br/>
        /// Windows is removing this device. <br/>
        /// 22     This device is disabled. <br/>
        /// 23     System failure: Try changing the driver for this device. <br/>
        /// If that doesn&apos;t work, see your hardware documentation. <br/>
        /// 24     This device is not present, is not working properly, or does not have all its drivers installed. <br/>
        /// 25     Windows is still setting up this device. <br/>
        /// 26     Windows is still setting up this device. <br/>
        /// 27     This device does not have valid log configuration. <br/>
        /// 28     The drivers for this device are not installed. <br/>
        /// 29     This device is disabled because the firmware of the device did not give it the required resources. <br/>
        /// 30     This device is using an Interrupt Request (IRQ) resource that another device is using. <br/>
        /// 31     This device is not working properly because Windows cannot load the drivers required for this device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ConfigManagerErrorCode { get; set; }
        /// <summary>
        /// Indicates whether the device is using a user-defined configuration. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ConfigManagerUserConfig { get; set; }
        /// <summary>
        /// CreationClassName indicates the name of the class or the subclass used in the creation of an instance. <br/>
        /// When used with the other key properties of this class, this property allows all instances of this class and its subclasses to be uniquely identified. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CreationClassName { get; set; }
        /// <summary>
        /// The Description property provides a textual description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The DeviceID property contains a string identifying the heat pipe. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: DeviceId <br/>
        ///  <br/>
        /// </summary>
        public String DeviceID { get; set; }
        /// <summary>
        /// ErrorCleared is a boolean property indicating that the error reported in LastErrorCode property is now cleared. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ErrorCleared { get; set; }
        /// <summary>
        /// ErrorDescription is a free-form string supplying more information about the error recorded in LastErrorCode property, and information on any corrective actions that may be taken. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ErrorDescription { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// LastErrorCode captures the last error code reported by the logical device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 LastErrorCode { get; set; }
        /// <summary>
        /// The Name property defines the label by which the object is known. <br/>
        /// When subclassed, the Name property can be overridden to be a Key property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// Indicates the Win32 Plug and Play device ID of the logical device. <br/>
        /// Example: *PNP030b <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String PNPDeviceID { get; set; }
        /// <summary>
        /// Indicates the specific power-related capabilities of the logical device. <br/>
        /// The array values, 0=&quot;Unknown&quot;, 1=&quot;Not Supported&quot; and 2=&quot;Disabled&quot; are self-explanatory. <br/>
        /// The value, 3=&quot;Enabled&quot; indicates that the power management features are currently enabled but the exact feature set is unknown or the information is unavailable. <br/>
        /// &quot;Power Saving Modes Entered Automatically&quot; (4) describes that a device can change its power state based on usage or other criteria. <br/>
        /// &quot;Power State Settable&quot; (5) indicates that the SetPowerState method is supported. <br/>
        /// &quot;Power Cycling Supported&quot; (6) indicates that the SetPowerState method can be invoked with the PowerState input variable set to 5 (&quot;Power Cycle&quot;). <br/>
        /// &quot;Timed Power On Supported&quot; (7) indicates that the SetPowerState method can be invoked with the PowerState input variable set to 5 (&quot;Power Cycle&quot;) and the Time parameter set to a specific date and time, or interval, for power-on. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16[] PowerManagementCapabilities { get; set; }
        /// <summary>
        /// Boolean indicating that the Device can be power managed - ie, put into a power save state. <br/>
        /// This boolean does not indicate that power management features are currently enabled, or if enabled, what features are supported. <br/>
        /// Refer to the PowerManagementCapabilities array for this information. <br/>
        /// If this boolean is false, the integer value 1, for the string, &quot;Not Supported&quot;, should be the only entry in the PowerManagementCapabilities array. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean PowerManagementSupported { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// StatusInfo is a string indicating whether the logical device is in an enabled (value = 3), disabled (value = 4) or some other (1) or unknown (2) state. <br/>
        /// If this property does not apply to the logical device, the value, 5 (&quot;Not Applicable&quot;), should be used. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 StatusInfo { get; set; }
        /// <summary>
        /// The scoping System&apos;s CreationClassName. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.CreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String SystemCreationClassName { get; set; }
        /// <summary>
        /// The scoping System&apos;s Name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.Name <br/>
        ///  <br/>
        /// </summary>
        public String SystemName { get; set; }
    }
}
