// <auto-generated />

using System;

namespace CIMV2
{
    /// <summary>
    /// The Win32_IP4RouteTableEvent class represents IP route change events resulting from the addition, removal or modification of IP routes on the computer system. <br/>
    ///  <br/>
    /// uuid: {1C385E29-A5B4-40F0-96CF-929FC00958B} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_IP4RouteTableEvent
    {
        /// <summary>
        ///  <br/>
        /// cimtype: uint8 <br/>
        ///  <br/>
        /// </summary>
        public byte[] SECURITY_DESCRIPTOR { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// </summary>
        public UInt64 TIME_CREATED { get; set; }
    }

    /// <summary>
    /// The Win32_InfraredDevice class represents the capabilities and management of an infrared device. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {67F74295-BA42-11d2-85E5-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_InfraredDevice
    {
        /// <summary>
        /// The availability and status of the device. <br/>
        /// For example, the Availability property indicates that the device is running and has full power (value=3), or is in a warning (4), test (5), degraded (10) or power save state (values 13-15 and 17). <br/>
        /// Regarding the power saving states, these are defined as follows: Value 13 (&quot;Power Save - Unknown&quot;) indicates that the device is known to be in a power save mode, but its exact status in this mode is unknown; 14 (&quot;Power Save - Low Power Mode&quot;) indicates that the device is in a power save state but still functioning, and may exhibit degraded performance; 15 (&quot;Power Save - Standby&quot;) describes that the device is not functioning but could be brought to full power &apos;quickly&apos;; and value 17 (&quot;Power Save - Warning&quot;) indicates that the device is in a warning state, though also in a power save mode. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 Availability { get; set; }
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// Indicates the Win32 Configuration Manager error code. <br/>
        /// The following values may be returned: <br/>
        /// 0      This device is working properly. <br/>
        /// 1      This device is not configured correctly. <br/>
        /// 2      Windows cannot load the driver for this device. <br/>
        /// 3      The driver for this device might be corrupted, or your system may be running low on memory or other resources. <br/>
        /// 4      This device is not working properly. <br/>
        /// One of its drivers or your registry might be corrupted. <br/>
        /// 5      The driver for this device needs a resource that Windows cannot manage. <br/>
        /// 6      The boot configuration for this device conflicts with other devices. <br/>
        /// 7      Cannot filter. <br/>
        /// 8      The driver loader for the device is missing. <br/>
        /// 9      This device is not working properly because the controlling firmware is reporting the resources for the device incorrectly. <br/>
        /// 10     This device cannot start. <br/>
        /// 11     This device failed. <br/>
        /// 12     This device cannot find enough free resources that it can use. <br/>
        /// 13     Windows cannot verify this device&apos;s resources. <br/>
        /// 14     This device cannot work properly until you restart your computer. <br/>
        /// 15     This device is not working properly because there is probably a re-enumeration problem. <br/>
        /// 16     Windows cannot identify all the resources this device uses. <br/>
        /// 17     This device is asking for an unknown resource type. <br/>
        /// 18     Reinstall the drivers for this device. <br/>
        /// 19     Your registry might be corrupted. <br/>
        /// 20     Failure using the VxD loader. <br/>
        /// 21     System failure: Try changing the driver for this device. <br/>
        /// If that does not work, see your hardware documentation. <br/>
        /// Windows is removing this device. <br/>
        /// 22     This device is disabled. <br/>
        /// 23     System failure: Try changing the driver for this device. <br/>
        /// If that doesn&apos;t work, see your hardware documentation. <br/>
        /// 24     This device is not present, is not working properly, or does not have all its drivers installed. <br/>
        /// 25     Windows is still setting up this device. <br/>
        /// 26     Windows is still setting up this device. <br/>
        /// 27     This device does not have valid log configuration. <br/>
        /// 28     The drivers for this device are not installed. <br/>
        /// 29     This device is disabled because the firmware of the device did not give it the required resources. <br/>
        /// 30     This device is using an Interrupt Request (IRQ) resource that another device is using. <br/>
        /// 31     This device is not working properly because Windows cannot load the drivers required for this device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ConfigManagerErrorCode { get; set; }
        /// <summary>
        /// Indicates whether the device is using a user-defined configuration. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ConfigManagerUserConfig { get; set; }
        /// <summary>
        /// CreationClassName indicates the name of the class or the subclass used in the creation of an instance. <br/>
        /// When used with the other key properties of this class, this property allows all instances of this class and its subclasses to be uniquely identified. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CreationClassName { get; set; }
        /// <summary>
        /// The Description property provides a textual description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The DeviceID property contains a string uniquely identifying the infrared device with other devices on the system. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: DeviceId <br/>
        ///  <br/>
        /// </summary>
        public String DeviceID { get; set; }
        /// <summary>
        /// ErrorCleared is a boolean property indicating that the error reported in LastErrorCode property is now cleared. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ErrorCleared { get; set; }
        /// <summary>
        /// ErrorDescription is a free-form string supplying more information about the error recorded in LastErrorCode property, and information on any corrective actions that may be taken. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ErrorDescription { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// LastErrorCode captures the last error code reported by the logical device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 LastErrorCode { get; set; }
        /// <summary>
        /// The Manufacturer property indicates the name of the manufacturer of the infrared device . <br/>
        /// Example: Acme <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Manufacturer { get; set; }
        /// <summary>
        /// Maximum number of directly addressable entities supported by this Controller. <br/>
        /// A value of 0 should be used if the number is unknown or unlimited. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 MaxNumberControlled { get; set; }
        /// <summary>
        /// The Name property defines the label by which the object is known. <br/>
        /// When subclassed, the Name property can be overridden to be a Key property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// Indicates the Win32 Plug and Play device ID of the logical device. <br/>
        /// Example: *PNP030b <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String PNPDeviceID { get; set; }
        /// <summary>
        /// Indicates the specific power-related capabilities of the logical device. <br/>
        /// The array values, 0=&quot;Unknown&quot;, 1=&quot;Not Supported&quot; and 2=&quot;Disabled&quot; are self-explanatory. <br/>
        /// The value, 3=&quot;Enabled&quot; indicates that the power management features are currently enabled but the exact feature set is unknown or the information is unavailable. <br/>
        /// &quot;Power Saving Modes Entered Automatically&quot; (4) describes that a device can change its power state based on usage or other criteria. <br/>
        /// &quot;Power State Settable&quot; (5) indicates that the SetPowerState method is supported. <br/>
        /// &quot;Power Cycling Supported&quot; (6) indicates that the SetPowerState method can be invoked with the PowerState input variable set to 5 (&quot;Power Cycle&quot;). <br/>
        /// &quot;Timed Power On Supported&quot; (7) indicates that the SetPowerState method can be invoked with the PowerState input variable set to 5 (&quot;Power Cycle&quot;) and the Time parameter set to a specific date and time, or interval, for power-on. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16[] PowerManagementCapabilities { get; set; }
        /// <summary>
        /// Boolean indicating that the Device can be power managed - ie, put into a power save state. <br/>
        /// This boolean does not indicate that power management features are currently enabled, or if enabled, what features are supported. <br/>
        /// Refer to the PowerManagementCapabilities array for this information. <br/>
        /// If this boolean is false, the integer value 1, for the string, &quot;Not Supported&quot;, should be the only entry in the PowerManagementCapabilities array. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean PowerManagementSupported { get; set; }
        /// <summary>
        /// The protocol used by the controller to access &apos;controlled&apos; devices. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 ProtocolSupported { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// StatusInfo is a string indicating whether the logical device is in an enabled (value = 3), disabled (value = 4) or some other (1) or unknown (2) state. <br/>
        /// If this property does not apply to the logical device, the value, 5 (&quot;Not Applicable&quot;), should be used. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 StatusInfo { get; set; }
        /// <summary>
        /// The scoping System&apos;s CreationClassName. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.CreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String SystemCreationClassName { get; set; }
        /// <summary>
        /// The scoping System&apos;s Name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.Name <br/>
        ///  <br/>
        /// </summary>
        public String SystemName { get; set; }
        /// <summary>
        /// The TimeOfLastReset property indicates the date and time this controller was last reset. <br/>
        /// This could mean the controller was powered down, or reinitialized. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime TimeOfLastReset { get; set; }
    }

    /// <summary>
    /// The Win32_IDEController class manages the capabilities of an IDE controller device. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {9ABA5122-C7A1-11d2-911D-0060081A46FD} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_IDEController
    {
        /// <summary>
        /// The availability and status of the device. <br/>
        /// For example, the Availability property indicates that the device is running and has full power (value=3), or is in a warning (4), test (5), degraded (10) or power save state (values 13-15 and 17). <br/>
        /// Regarding the power saving states, these are defined as follows: Value 13 (&quot;Power Save - Unknown&quot;) indicates that the device is known to be in a power save mode, but its exact status in this mode is unknown; 14 (&quot;Power Save - Low Power Mode&quot;) indicates that the device is in a power save state but still functioning, and may exhibit degraded performance; 15 (&quot;Power Save - Standby&quot;) describes that the device is not functioning but could be brought to full power &apos;quickly&apos;; and value 17 (&quot;Power Save - Warning&quot;) indicates that the device is in a warning state, though also in a power save mode. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 Availability { get; set; }
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// Indicates the Win32 Configuration Manager error code. <br/>
        /// The following values may be returned: <br/>
        /// 0      This device is working properly. <br/>
        /// 1      This device is not configured correctly. <br/>
        /// 2      Windows cannot load the driver for this device. <br/>
        /// 3      The driver for this device might be corrupted, or your system may be running low on memory or other resources. <br/>
        /// 4      This device is not working properly. <br/>
        /// One of its drivers or your registry might be corrupted. <br/>
        /// 5      The driver for this device needs a resource that Windows cannot manage. <br/>
        /// 6      The boot configuration for this device conflicts with other devices. <br/>
        /// 7      Cannot filter. <br/>
        /// 8      The driver loader for the device is missing. <br/>
        /// 9      This device is not working properly because the controlling firmware is reporting the resources for the device incorrectly. <br/>
        /// 10     This device cannot start. <br/>
        /// 11     This device failed. <br/>
        /// 12     This device cannot find enough free resources that it can use. <br/>
        /// 13     Windows cannot verify this device&apos;s resources. <br/>
        /// 14     This device cannot work properly until you restart your computer. <br/>
        /// 15     This device is not working properly because there is probably a re-enumeration problem. <br/>
        /// 16     Windows cannot identify all the resources this device uses. <br/>
        /// 17     This device is asking for an unknown resource type. <br/>
        /// 18     Reinstall the drivers for this device. <br/>
        /// 19     Your registry might be corrupted. <br/>
        /// 20     Failure using the VxD loader. <br/>
        /// 21     System failure: Try changing the driver for this device. <br/>
        /// If that does not work, see your hardware documentation. <br/>
        /// Windows is removing this device. <br/>
        /// 22     This device is disabled. <br/>
        /// 23     System failure: Try changing the driver for this device. <br/>
        /// If that doesn&apos;t work, see your hardware documentation. <br/>
        /// 24     This device is not present, is not working properly, or does not have all its drivers installed. <br/>
        /// 25     Windows is still setting up this device. <br/>
        /// 26     Windows is still setting up this device. <br/>
        /// 27     This device does not have valid log configuration. <br/>
        /// 28     The drivers for this device are not installed. <br/>
        /// 29     This device is disabled because the firmware of the device did not give it the required resources. <br/>
        /// 30     This device is using an Interrupt Request (IRQ) resource that another device is using. <br/>
        /// 31     This device is not working properly because Windows cannot load the drivers required for this device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 ConfigManagerErrorCode { get; set; }
        /// <summary>
        /// Indicates whether the device is using a user-defined configuration. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ConfigManagerUserConfig { get; set; }
        /// <summary>
        /// CreationClassName indicates the name of the class or the subclass used in the creation of an instance. <br/>
        /// When used with the other key properties of this class, this property allows all instances of this class and its subclasses to be uniquely identified. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CreationClassName { get; set; }
        /// <summary>
        /// The Description property provides a textual description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The DeviceID property indicates a string that uniquely identifies the IDE controller with other devices on the system. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// override: DeviceId <br/>
        ///  <br/>
        /// </summary>
        public String DeviceID { get; set; }
        /// <summary>
        /// ErrorCleared is a boolean property indicating that the error reported in LastErrorCode property is now cleared. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean ErrorCleared { get; set; }
        /// <summary>
        /// ErrorDescription is a free-form string supplying more information about the error recorded in LastErrorCode property, and information on any corrective actions that may be taken. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ErrorDescription { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// LastErrorCode captures the last error code reported by the logical device. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 LastErrorCode { get; set; }
        /// <summary>
        /// The Manufacturer property indicates the manufacturer of the IDE controller device. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Manufacturer { get; set; }
        /// <summary>
        /// Maximum number of directly addressable entities supported by this Controller. <br/>
        /// A value of 0 should be used if the number is unknown or unlimited. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 MaxNumberControlled { get; set; }
        /// <summary>
        /// The Name property defines the label by which the object is known. <br/>
        /// When subclassed, the Name property can be overridden to be a Key property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// Indicates the Win32 Plug and Play device ID of the logical device. <br/>
        /// Example: *PNP030b <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String PNPDeviceID { get; set; }
        /// <summary>
        /// Indicates the specific power-related capabilities of the logical device. <br/>
        /// The array values, 0=&quot;Unknown&quot;, 1=&quot;Not Supported&quot; and 2=&quot;Disabled&quot; are self-explanatory. <br/>
        /// The value, 3=&quot;Enabled&quot; indicates that the power management features are currently enabled but the exact feature set is unknown or the information is unavailable. <br/>
        /// &quot;Power Saving Modes Entered Automatically&quot; (4) describes that a device can change its power state based on usage or other criteria. <br/>
        /// &quot;Power State Settable&quot; (5) indicates that the SetPowerState method is supported. <br/>
        /// &quot;Power Cycling Supported&quot; (6) indicates that the SetPowerState method can be invoked with the PowerState input variable set to 5 (&quot;Power Cycle&quot;). <br/>
        /// &quot;Timed Power On Supported&quot; (7) indicates that the SetPowerState method can be invoked with the PowerState input variable set to 5 (&quot;Power Cycle&quot;) and the Time parameter set to a specific date and time, or interval, for power-on. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16[] PowerManagementCapabilities { get; set; }
        /// <summary>
        /// Boolean indicating that the Device can be power managed - ie, put into a power save state. <br/>
        /// This boolean does not indicate that power management features are currently enabled, or if enabled, what features are supported. <br/>
        /// Refer to the PowerManagementCapabilities array for this information. <br/>
        /// If this boolean is false, the integer value 1, for the string, &quot;Not Supported&quot;, should be the only entry in the PowerManagementCapabilities array. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean PowerManagementSupported { get; set; }
        /// <summary>
        /// The protocol used by the controller to access &apos;controlled&apos; devices. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 ProtocolSupported { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// StatusInfo is a string indicating whether the logical device is in an enabled (value = 3), disabled (value = 4) or some other (1) or unknown (2) state. <br/>
        /// If this property does not apply to the logical device, the value, 5 (&quot;Not Applicable&quot;), should be used. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 StatusInfo { get; set; }
        /// <summary>
        /// The scoping System&apos;s CreationClassName. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.CreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String SystemCreationClassName { get; set; }
        /// <summary>
        /// The scoping System&apos;s Name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_System.Name <br/>
        ///  <br/>
        /// </summary>
        public String SystemName { get; set; }
        /// <summary>
        /// The TimeOfLastReset property indicates the date and time this controller was last reset. <br/>
        /// This could mean the controller was powered down, or reinitialized. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime TimeOfLastReset { get; set; }
    }

    /// <summary>
    /// The Win32_IRQResource class represents an interrupt request line (IRQ) number on a Win32 computer system. <br/>
    /// An interrupt request is a signal sent to the CPU by a device or program for time critical events. <br/>
    /// IRQ can be hardware or software based. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {8502C4D3-5FBB-11D2-AAC1-006008C78BC7} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_IRQResource
    {
        /// <summary>
        /// Availability of the IRQ. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 Availability { get; set; }
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// CreationClassName indicates the name of the class or the subclass used in the creation of an instance. <br/>
        /// When used with the other key properties of this class, this property allows all instances of this class and its subclasses to be uniquely identified. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CreationClassName { get; set; }
        /// <summary>
        /// CSCreationClassName contains the scoping computer system&apos;s creation class name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_ComputerSystem.CreationClassName <br/>
        ///  <br/>
        /// </summary>
        public String CSCreationClassName { get; set; }
        /// <summary>
        /// CSName contains the scoping computer system&apos;s name. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_ComputerSystem.Name <br/>
        ///  <br/>
        /// </summary>
        public String CSName { get; set; }
        /// <summary>
        /// The Description property provides a textual description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The Hardware property indicates whether the interrupt is hardware or software based. <br/>
        /// A hardware IRQ is a physical wire from the peripheral to the programmable interrupt controller (PIC) chip through which the CPU can be notified of time critical events. <br/>
        /// Some IRQ lines are reserved for standard devices such as the keyboard, floppy disk drives, and the system clock. <br/>
        /// A software interrupt allows applications to get the attention of the processor. <br/>
        /// Values: TRUE or FALSE. <br/>
        /// A value of TRUE indicates the interrupt is hardware based. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Hardware { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// A part of the object&apos;s key value, IRQ Number. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 IRQNumber { get; set; }
        /// <summary>
        /// The Name property defines the label by which the object is known. <br/>
        /// When subclassed, the Name property can be overridden to be a Key property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// Boolean indicating whether the IRQ can be shared. <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean Shareable { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// IRQ trigger level indicating whether the interrupt is triggered by the hardware signal going high (value=4) or low (value=3). <br/>
        /// Also, &quot;Other&quot; (1) and &quot;Unknown&quot; (2) may be defined. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 TriggerLevel { get; set; }
        /// <summary>
        /// IRQ trigger type indicating whether edge (value=4) or level triggered (value=3) interrupts occur. <br/>
        /// Also, &quot;Other&quot; (1) and &quot;Unknown&quot; (2) may be defined. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 TriggerType { get; set; }
        /// <summary>
        /// The Vector property indicates the vector of the Win32 IRQ resource. <br/>
        /// A vector contains the memory address to the function that will execute once the CPU acknowledges the interrupt request. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Vector { get; set; }
    }

    /// <summary>
    /// The IP4RouteTable class information governs where network data packets are routed to (e.g. <br/>
    /// usually internet packets are sent to a gateway, and local packets may be routed directly by the client&apos;s machine). <br/>
    /// Administrators can use this information to trace problems associated with misrouted packets, and also direct a computer to a new gateway as necessary. <br/>
    /// This class deals specifically with IP4 and does not address IPX or IP6. <br/>
    /// It is only intended to model the information revealed when typing the &apos;Route Print&apos; command from the command prompt. <br/>
    /// Please Note: though updating instances of this class is supported, supplying property values which are invalid or unrecognized by the network protocol stack will not update successfully and the original values will persist. <br/>
    /// An error is not guaranteed to be generated when this happens, but if one does, nothing is updated. <br/>
    ///  <br/>
    /// createby: PutInstance <br/>
    ///  <br/>
    /// deleteby: DeleteInstance <br/>
    ///  <br/>
    /// provider: RouteProvider <br/>
    ///  <br/>
    /// uuid: {ABEE8C61-A43F-4088-0081-9D00B3FF6545} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_IP4RouteTable
    {
        /// <summary>
        /// The Age property contains the number of seconds since this route was last updated or otherwise determined to be correct. <br/>
        /// No semantics of &apos;too old&apos; can be implied except through knowledge of the routing protocol by which the route was learned. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Age { get; set; }
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// The Description property provides a textual description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The Destination property contains the destination IP address for this route. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Destination { get; set; }
        /// <summary>
        /// The Information property contains a reference to MIB definitions specific to the particular routing protocol that is responsible for this route, as determined by the value specified in the route&apos;s ipRouteProto value. <br/>
        /// If this information is not present, its value should be set to the OBJECT IDENTIFIER {0 0}, which is a syntactically valid object identifier, and any conformant implementation of ASN.1 and BER must be able to generate and recognize this value. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Information { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// The InterfaceIndex property contains the index value that uniquely identifies the local interface through which the next hop of this route should be reached. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// </summary>
        public int InterfaceIndex { get; set; }
        /// <summary>
        /// The Mask property contains the mask used in this entry. <br/>
        /// Masks should be logical-ANDed with the destination address before being compared to the value in the ipRouteDest field. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Mask { get; set; }
        /// <summary>
        /// The Metric1 property contains the primary routing metric for this route. <br/>
        /// The semantics of this metric are determined by the routing protocol specified in the route&apos;s ipRouteProto value. <br/>
        /// If this metric is not used, its value should be set to -1. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// </summary>
        public int Metric1 { get; set; }
        /// <summary>
        /// The Metric2 property contains an alternate routing metric for this route. <br/>
        /// The semantics of this metric are determined by the routing protocol specified in the route&apos;s ipRouteProto value. <br/>
        /// If this metric is not used, its value should be set to -1. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// </summary>
        public int Metric2 { get; set; }
        /// <summary>
        /// The Metric3 property contains an alternate routing metric for this route. <br/>
        /// The semantics of this metric are determined by the routing protocol specified in the route&apos;s ipRouteProto value. <br/>
        /// If this metric is not used, its value should be set to -1. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// </summary>
        public int Metric3 { get; set; }
        /// <summary>
        /// The Metric4 property contains an alternate routing metric for this route. <br/>
        /// The semantics of this metric are determined by the routing protocol specified in the route&apos;s ipRouteProto value. <br/>
        /// If this metric is not used, its value should be set to -1. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// </summary>
        public int Metric4 { get; set; }
        /// <summary>
        /// The Metric5 property contains an alternate routing metric for this route. <br/>
        /// The semantics of this metric are determined by the routing protocol specified in the route&apos;s ipRouteProto value. <br/>
        /// If this metric is not used, its value should be set to -1. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// </summary>
        public int Metric5 { get; set; }
        /// <summary>
        /// The Name property defines the label by which the object is known. <br/>
        /// When subclassed, the Name property can be overridden to be a Key property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The NextHop property contains the IP address of the next hop of this route. <br/>
        /// (In the case of a route bound to an interface that is realized via a broadcast media, the value of this field is the agent&apos;s IP address on that interface.). <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String NextHop { get; set; }
        /// <summary>
        /// The Protocol property reveals the routing mechanism via which this route was learned. <br/>
        /// Inclusion of values for gateway routing protocols is not intended to imply that hosts must support those protocols. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Protocol { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
        /// <summary>
        /// The Type property reveals the type of route. <br/>
        /// The values direct(3) and indirect(4) refer to the notion of direct and indirect routing in the IP architecture. <br/>
        /// Setting this object to the value invalid(2) has the effect of invalidating the corresponding entry in the RouteTable object. <br/>
        /// That is, it effectively disassociates the destination identified with said entry from the route identified with said entry. <br/>
        /// It is an implementation-specific matter as to whether the agent removes an invalidated entry from the table. <br/>
        /// Accordingly, management stations must be prepared to receive tabular information from agents that corresponds to entries not currently in use. <br/>
        /// Proper interpretation of such entries requires examination of the relevant ipRouteType object. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 Type { get; set; }
    }

    /// <summary>
    /// The IP4PersistedRouteTable class contains IP routes that are persisted. <br/>
    /// By default, the routes you add to the routing table aren&apos;t permanent. <br/>
    /// You lose these routes when you reboot your computer. <br/>
    /// However, if you use the command route -p add, Windows NT makes the permanent--so you won&apos;t lose the route when you reboot your computer. <br/>
    /// Persistent entries are automatically reinserted in your route table each time your computer&apos;s route table is rebuilt. <br/>
    /// Windows NT stores persistent routes in the Registry. <br/>
    /// This class deals specifically with IP4 and does not address IPX or IP6. <br/>
    ///  <br/>
    /// createby: PutInstance <br/>
    ///  <br/>
    /// deleteby: DeleteInstance <br/>
    ///  <br/>
    /// provider: RouteProvider <br/>
    ///  <br/>
    /// uuid: {2CAF4666-AC9B-45AB-00A6-AF8C537794C2} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_IP4PersistedRouteTable
    {
        /// <summary>
        /// The Caption property is a short textual description (one-line string) of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// The Description property provides a textual description of the object. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        /// The Destination property contains the destination IP address for this persisted route. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Destination { get; set; }
        /// <summary>
        /// The InstallDate property is datetime value indicating when the object was installed. <br/>
        /// A lack of a value does not indicate that the object is not installed. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime InstallDate { get; set; }
        /// <summary>
        /// The Mask property contains the mask used in this persisted entry. <br/>
        /// Masks should be logical-ANDed with the destination address before being compared to the value in the ipRouteDest field. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Mask { get; set; }
        /// <summary>
        /// The Metric1 property contains the primary routing metric for this persisted route. <br/>
        /// The semantics of this metric are determined by the routing protocol specified in the route&apos;s ipRouteProto value. <br/>
        /// If this metric is not used, its value should be set to -1. <br/>
        ///  <br/>
        /// cimtype: sint32 <br/>
        ///  <br/>
        /// </summary>
        public int Metric1 { get; set; }
        /// <summary>
        /// The Name property defines the label by which the object is known. <br/>
        /// When subclassed, the Name property can be overridden to be a Key property. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The NextHop property contains the IP address of the next hop of this persisted route. <br/>
        /// (In the case of a route bound to an interface that is realized via a broadcast media, the value of this field is the agent&apos;s IP address on that interface.). <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String NextHop { get; set; }
        /// <summary>
        /// The Status property is a string indicating the current status of the object. <br/>
        /// Various operational and non-operational statuses can be defined. <br/>
        /// Operational statuses are &quot;OK&quot;, &quot;Degraded&quot; and &quot;Pred Fail&quot;. <br/>
        /// &quot;Pred Fail&quot; indicates that an element may be functioning properly but predicting a failure in the near future. <br/>
        /// An example is a SMART-enabled hard drive. <br/>
        /// Non-operational statuses can also be specified. <br/>
        /// These are &quot;Error&quot;, &quot;Starting&quot;, &quot;Stopping&quot; and &quot;Service&quot;. <br/>
        /// The latter, &quot;Service&quot;, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. <br/>
        /// Not all such work is on-line, yet the managed element is neither &quot;OK&quot; nor in one of the other states. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Status { get; set; }
    }

    /// <summary>
    /// The Win32_InstalledStoreProgram class represents an installed store application. <br/>
    ///  <br/>
    /// provider: InvProv <br/>
    ///  <br/>
    /// uuid: {13DAD3AD-9F41-4722-8DEB-7D151C1E4F9B} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_InstalledStoreProgram
    {
        /// <summary>
        /// Program architecture <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Architecture { get; set; }
        /// <summary>
        /// Program language <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Language { get; set; }
        /// <summary>
        /// Program name <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// Unique identifier of program <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ProgramId { get; set; }
        /// <summary>
        /// Program vendor <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Vendor { get; set; }
        /// <summary>
        /// Program version <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Version { get; set; }
    }

    /// <summary>
    /// The Win32_IDEControllerDevice class represents an association between an Integrated Drive Electronics (IDE) controller and the logical device, for example, a disk drive, connected to it. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {5BC42B62-C7A1-11d2-911D-0060081A46FD} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_IDEControllerDevice
    {
        /// <summary>
        /// The AccessState property indicates whether the controller is actively commanding or accessing the device (value=1) or not (value=2). <br/>
        /// Also, the value, &quot;Unknown&quot; (0), can be defined. <br/>
        /// This information is necessary when a logical device can be commanded by, or accessed through, multiple controllers. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 AccessState { get; set; }
        /// <summary>
        /// When several bus and/or connection data widths are possible, the NegotiatedDataWidth property defines the one in use between the devices. <br/>
        /// Data width is specified in bits. <br/>
        /// If data width is not negotiated, or if this information is not available/important to device management, the property should be set to 0. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// units: bits <br/>
        ///  <br/>
        /// </summary>
        public UInt32 NegotiatedDataWidth { get; set; }
        /// <summary>
        /// When several bus and/or connection speeds are possible, the NegotiatedSpeed property defines the one in use between the devices. <br/>
        /// Speed is specified in bits per second. <br/>
        /// If connection or bus speeds are not negotiated, or if this information is not available/important to device management, the property should be set to 0. <br/>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: bits per second <br/>
        ///  <br/>
        /// </summary>
        public UInt64 NegotiatedSpeed { get; set; }
        /// <summary>
        /// Number of hard resets issued by the controller. <br/>
        /// A hard reset returns the device to its initialization or &apos;boot-up&apos; state. <br/>
        /// All internal device state information and data are lost. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 NumberOfHardResets { get; set; }
        /// <summary>
        /// Number of soft resets issued by the controller. <br/>
        /// A soft reset does not completely clear current device state and/or data. <br/>
        /// Exact semantics are dependent on the device, and on the protocols and mechanisms used to communicate to it. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 NumberOfSoftResets { get; set; }
    }

    /// <summary>
    /// The Win32_ImplementedCategory class represents an association between a component category and the COM classusing its interfaces. <br/>
    ///  <br/>
    /// locale: ms_409 <br/>
    ///  <br/>
    /// provider: CIMWin32 <br/>
    ///  <br/>
    /// uuid: {0F73ED5B-8ED9-11d2-B340-00105A1F8569} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_ImplementedCategory
    {
    }

    /// <summary>
    /// The InstalledSoftwareElement association allows one to  to identify the Computer System a particular Software element is installed on. <br/>
    ///  <br/>
    /// provider: MSIProv <br/>
    ///  <br/>
    /// uuid: {DB91D602-DB32-11d2-85FC-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_InstalledSoftwareElement
    {
    }

    /// <summary>
    /// This class contains the .INI information that the application needs to set in an .INI file. <br/>
    /// The .INI file information is written out when the corresponding component has been selected to be installed, either locally or run from source. <br/>
    ///  <br/>
    /// provider: MSIProv <br/>
    ///  <br/>
    /// uuid: {47772EC4-DB21-11d2-85FC-0000F8102E5F} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_IniFileSpecification
    {
        /// <summary>
        /// The type of modification made. <br/>
        /// Hexadecimal <br/>
        /// Decimal <br/>
        /// Modification <br/>
        /// 0x000 <br/>
        /// 0 <br/>
        /// Creates or updates a .ini entry. <br/>
        /// 0x001 <br/>
        /// 1 <br/>
        /// Creates a .ini entry only if the entry does not already exist. <br/>
        /// 0x003 <br/>
        /// 3 <br/>
        /// Creates a new entry or appends a new comma-separated value to an existing entry. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// </summary>
        public UInt16 Action { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Caption { get; set; }
        /// <summary>
        /// An identifier used in conjunction with other keys to uniquely identify the check <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String CheckID { get; set; }
        /// <summary>
        /// The CheckMode property is used to indicate whether the condition is  expected to exist or not exist in the environment. <br/>
        /// When the value is True, the condition is expected to exist  (e.g., a file is expected to be on a system) so invoke() is expected to  return True. <br/>
        /// When the value is False, the condition is not expect to exist  (e.g., a file is not to be on a system) so invoke is expected to return false <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean CheckMode { get; set; }
        /// <summary>
        /// The Checksum property is a checksum calculated as the 16-bit  sum of the first 32 bytes of the file. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 CheckSum { get; set; }
        /// <summary>
        /// The CRC1 property is the CRC value calculated using the middle  512K bytes. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 CRC1 { get; set; }
        /// <summary>
        /// The CRC2 is the CRC value for the middle 512K bytes with a  offset modulo 3 to the start of the file of zero. <br/>
        ///  <br/>
        /// cimtype: uint32 <br/>
        ///  <br/>
        /// </summary>
        public UInt32 CRC2 { get; set; }
        /// <summary>
        /// The creation date and time of the file. <br/>
        ///  <br/>
        /// cimtype: datetime <br/>
        ///  <br/>
        /// </summary>
        public DateTime CreateTimeStamp { get; set; }
        /// <summary>
        /// A description of the objects. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Description { get; set; }
        /// <summary>
        ///  <br/>
        /// cimtype: uint64 <br/>
        ///  <br/>
        /// units: kilobytes <br/>
        ///  <br/>
        /// </summary>
        public UInt64 FileSize { get; set; }
        /// <summary>
        /// A unique key identifying this ini file specification within its product. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String IniFile { get; set; }
        /// <summary>
        /// The .ini file key within the section. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String key { get; set; }
        /// <summary>
        /// The MD5 algorithm is a well-known algorithm for computing a 128-bit  checksum for any file or object. <br/>
        /// The likelihood of two different   files producing the same MD5 checksum is very small  (about 1 in 2^64), and as such, the MD5 checksum of a file can be  used to construct a reliable content identifier that is very  likely to uniquely identify the file. <br/>
        /// The reverse is also true. <br/>
        /// If two files have the same MD5 checksum, it is very likely that  the files are identical. <br/>
        /// For purposes of MOF specification  of the MD5 property, the MD5 algorithm always generates a 32  character string. <br/>
        /// For example: The string abcdefghijklmnopqrstuvwxyz  generates the string c3fcd3d76192e4007dfb496cca67e13b. <br/>
        /// See http://www. <br/>
        /// rsa.com/pub/rfc1321.txt for details on the implementation of the MD5  algorithm. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String MD5Checksum { get; set; }
        /// <summary>
        /// Either the name of the file or the name of the file with a  directory prefix. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.Name <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// The .ini file section. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Section { get; set; }
        /// <summary>
        /// This is an identifier for this software element. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementID <br/>
        ///  <br/>
        /// </summary>
        public String SoftwareElementID { get; set; }
        /// <summary>
        /// The software element state of a software element <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.SoftwareElementState <br/>
        ///  <br/>
        /// </summary>
        public UInt16 SoftwareElementState { get; set; }
        /// <summary>
        /// The target operating system of the this software element. <br/>
        ///  <br/>
        /// cimtype: uint16 <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.TargetOperatingSystem <br/>
        ///  <br/>
        /// </summary>
        public UInt16 TargetOperatingSystem { get; set; }
        /// <summary>
        /// The value to be written. <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Value { get; set; }
        /// <summary>
        /// Version should be in the form &lt;Major&gt;.&lt;Minor&gt;.&lt;Revision&gt; or &lt;Major&gt;.&lt;Minor&gt;&lt;letter&gt;&lt;revision&gt; <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// propagated: CIM_SoftwareElement.Version <br/>
        ///  <br/>
        /// </summary>
        public String Version { get; set; }
    }

    /// <summary>
    /// The Win32_InstalledWin32Program class represents an installed Win32 application. <br/>
    ///  <br/>
    /// provider: InvProv <br/>
    ///  <br/>
    /// uuid: {455C66F5-2F69-4113-AF2F-ED22F1473B28} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_InstalledWin32Program
    {
        /// <summary>
        /// Program language <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Language { get; set; }
        /// <summary>
        /// MSI Package code <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String MsiPackageCode { get; set; }
        /// <summary>
        /// MSI Product code <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String MsiProductCode { get; set; }
        /// <summary>
        /// Program name <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Name { get; set; }
        /// <summary>
        /// Unique identifier of program <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ProgramId { get; set; }
        /// <summary>
        /// Program vendor <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Vendor { get; set; }
        /// <summary>
        /// Program version <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String Version { get; set; }
    }

    /// <summary>
    /// The Win32_InstalledProgramFramework class represents a framework that a Win32_InstalledWin32Program instance depends on. <br/>
    ///  <br/>
    /// provider: InvProv <br/>
    ///  <br/>
    /// uuid: {17087075-EB55-4FCC-ADAB-79B04E16ED04} <br/>
    ///  <br/>
    /// </summary>
    public class Win32_InstalledProgramFramework
    {
        /// <summary>
        /// Framework name <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String FrameworkName { get; set; }
        /// <summary>
        /// Framework publisher <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String FrameworkPublisher { get; set; }
        /// <summary>
        /// Framework version <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String FrameworkVersion { get; set; }
        /// <summary>
        /// Framework version actually used <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String FrameworkVersionActual { get; set; }
        /// <summary>
        /// TRUE if the framework is a private copy <br/>
        ///  <br/>
        /// cimtype: boolean <br/>
        ///  <br/>
        /// </summary>
        public Boolean IsPrivate { get; set; }
        /// <summary>
        /// Id of the Win32_InstalledWin32Program instance <br/>
        ///  <br/>
        /// cimtype: string <br/>
        ///  <br/>
        /// </summary>
        public String ProgramId { get; set; }
    }
}
