<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!--To fix the error The library 'hostpolicy.dll' required to execute the application was not found-->
    <OutputType>exe</OutputType>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <NoWarn>RS1035;CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FclEx.Core" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
  </ItemGroup>
</Project>