<Project>
  <Import Project="..\build\Package.props" />
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CS1591;CS8500;NU1900;NU5104</NoWarn>
    <Nullable>enable</Nullable>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <WarningsAsErrors>CS8785</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup>
    <IsWindows>$([MSBuild]::IsOSPlatform('Windows'))</IsWindows>
    <TargetFrameworkVersion>$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)', 2))</TargetFrameworkVersion>
  </PropertyGroup>
  <PropertyGroup>
    <!--System.Management only supports net8.0-windows and above. Do not try to add net6.0-windows or net7.0-windows, it won't work.-->
    <TargetFrameworks>net8.0-windows;net9.0-windows;net10.0-windows</TargetFrameworks>
  </PropertyGroup>
</Project>